# Generated by Django 6.0 on 2025-12-22 09:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Center",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("kb_module_name", models.CharField(default="unknown", max_length=255)),
                (
                    "examiner_uuids",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Citation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("kb_module_name", models.CharField(default="unknown", max_length=255)),
                ("citation_key", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=1024)),
                ("abstract", models.CharField(blank=True, max_length=5000, null=True)),
                ("authors", models.CharField(blank=True, max_length=2000)),
                ("publication_year", models.IntegerField(blank=True, null=True)),
                (
                    "publication_month",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("journal", models.CharField(blank=True, max_length=255, null=True)),
                ("publisher", models.CharField(blank=True, max_length=255, null=True)),
                ("volume", models.CharField(blank=True, max_length=50, null=True)),
                ("issue", models.CharField(blank=True, max_length=50, null=True)),
                ("pages", models.CharField(blank=True, max_length=50, null=True)),
                ("doi", models.CharField(blank=True, max_length=255, null=True)),
                ("url", models.CharField(blank=True, max_length=1024, null=True)),
                ("entry_type", models.CharField(blank=True, max_length=100, null=True)),
                ("language", models.CharField(blank=True, max_length=50, null=True)),
                ("keywords", models.CharField(blank=True, max_length=2000)),
                ("identifiers", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClassificationChoiceDescriptor",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("kb_module_name", models.CharField(default="unknown", max_length=255)),
                (
                    "descriptor_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("numeric", "numeric"),
                            ("text", "text"),
                            ("boolean", "boolean"),
                            ("selection", "selection"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("numeric_min", models.FloatField(blank=True, null=True)),
                ("numeric_max", models.FloatField(blank=True, null=True)),
                (
                    "numeric_distribution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("normal", "normal"),
                            ("uniform", "uniform"),
                            ("exponential", "exponential"),
                            ("unknown", "unknown"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "numeric_distribution_params",
                    models.JSONField(blank=True, default=dict),
                ),
                ("text_max_length", models.IntegerField(blank=True, null=True)),
                ("default_value_str", models.CharField(max_length=255)),
                ("default_value_num", models.FloatField()),
                ("default_value_bool", models.BooleanField()),
                ("selection_options", models.CharField(max_length=1000)),
                ("selection_multiple", models.BooleanField(default=False)),
                (
                    "selection_multiple_n_min",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "selection_multiple_n_max",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "selection_default_options",
                    models.JSONField(blank=True, default=dict),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClassificationType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("kb_module_name", models.CharField(default="unknown", max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExaminationType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("kb_module_name", models.CharField(default="unknown", max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Examiner",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("first_name", models.CharField(blank=True, max_length=150, null=True)),
                ("last_name", models.CharField(blank=True, max_length=150, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("female", "Female"),
                            ("male", "Male"),
                            ("other", "Other"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("street", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=20, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "center_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("external_ids", models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FindingType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("kb_module_name", models.CharField(default="unknown", max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Indication",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("kb_module_name", models.CharField(default="unknown", max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IndicationType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("kb_module_name", models.CharField(default="unknown", max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InformationSourceType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("kb_module_name", models.CharField(default="unknown", max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Intervention",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("kb_module_name", models.CharField(default="unknown", max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InterventionType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("kb_module_name", models.CharField(default="unknown", max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("first_name", models.CharField(blank=True, max_length=150, null=True)),
                ("last_name", models.CharField(blank=True, max_length=150, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("female", "Female"),
                            ("male", "Male"),
                            ("other", "Other"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("street", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=20, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "center_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("external_ids", models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("kb_module_name", models.CharField(default="unknown", max_length=255)),
                (
                    "abbreviation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UnitType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("kb_module_name", models.CharField(default="unknown", max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClassificationChoice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("kb_module_name", models.CharField(default="unknown", max_length=255)),
                (
                    "classification_choice_descriptors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="classification_choices",
                        to="lx_django.classificationchoicedescriptor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Classification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("kb_module_name", models.CharField(default="unknown", max_length=255)),
                (
                    "choices",
                    models.ManyToManyField(
                        blank=True,
                        related_name="classifications",
                        to="lx_django.classificationchoice",
                    ),
                ),
                (
                    "types",
                    models.ManyToManyField(
                        blank=True,
                        related_name="classifications",
                        to="lx_django.classificationtype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("kb_module_name", models.CharField(default="unknown", max_length=255)),
                (
                    "classifications",
                    models.ManyToManyField(
                        blank=True,
                        related_name="findings",
                        to="lx_django.classification",
                    ),
                ),
                (
                    "types",
                    models.ManyToManyField(
                        blank=True, related_name="findings", to="lx_django.findingtype"
                    ),
                ),
                (
                    "interventions",
                    models.ManyToManyField(
                        blank=True, related_name="findings", to="lx_django.intervention"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Examination",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("kb_module_name", models.CharField(default="unknown", max_length=255)),
                (
                    "types",
                    models.ManyToManyField(
                        blank=True,
                        related_name="examinations",
                        to="lx_django.examinationtype",
                    ),
                ),
                (
                    "findings",
                    models.ManyToManyField(
                        blank=True, related_name="examinations", to="lx_django.finding"
                    ),
                ),
                (
                    "indications",
                    models.ManyToManyField(
                        blank=True,
                        related_name="examinations",
                        to="lx_django.indication",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="indication",
            name="types",
            field=models.ManyToManyField(
                blank=True, related_name="indications", to="lx_django.indicationtype"
            ),
        ),
        migrations.CreateModel(
            name="InformationSource",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("kb_module_name", models.CharField(default="unknown", max_length=255)),
                (
                    "type_names",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                (
                    "types",
                    models.ManyToManyField(
                        blank=True,
                        related_name="information_sources",
                        to="lx_django.informationsourcetype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="indication",
            name="expected_interventions",
            field=models.ManyToManyField(
                blank=True, related_name="indications", to="lx_django.intervention"
            ),
        ),
        migrations.AddField(
            model_name="intervention",
            name="types",
            field=models.ManyToManyField(
                blank=True,
                related_name="interventions",
                to="lx_django.interventiontype",
            ),
        ),
        migrations.AddField(
            model_name="classificationchoicedescriptor",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classification_choice_descriptors",
                to="lx_django.unit",
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="types",
            field=models.ManyToManyField(
                blank=True, related_name="units", to="lx_django.unittype"
            ),
        ),
    ]
