# Generated by Django 6.0 on 2025-12-22 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lx_django", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="center",
            name="examiner_uuids",
        ),
        migrations.RemoveField(
            model_name="center",
            name="kb_module_name",
        ),
        migrations.RemoveField(
            model_name="examiner",
            name="center_name",
        ),
        migrations.AddField(
            model_name="examiner",
            name="center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="examiners",
                to="lx_django.center",
            ),
        ),
    ]
