# Generated by Django 6.0 on 2025-12-22 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lx_django", "0002_remove_center_examiner_uuids_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="center_name",
        ),
        migrations.AddField(
            model_name="patient",
            name="center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patients",
                to="lx_django.center",
            ),
        ),
    ]
