# Generated by Django 6.0 on 2025-12-18 09:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lx_django", "0003_center"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassificationChoiceDescriptor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name", models.CharField(max_length=255)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "descriptor_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("numeric", "numeric"),
                            ("text", "text"),
                            ("boolean", "boolean"),
                            ("selection", "selection"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("unit_name", models.CharField(blank=True, max_length=255, null=True)),
                ("numeric_min", models.FloatField(blank=True, null=True)),
                ("numeric_max", models.FloatField(blank=True, null=True)),
                (
                    "numeric_distribution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("normal", "normal"),
                            ("uniform", "uniform"),
                            ("exponential", "exponential"),
                            ("unknown", "unknown"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "numeric_distribution_params",
                    models.JSONField(blank=True, default=dict),
                ),
                ("text_max_length", models.IntegerField(blank=True, null=True)),
                ("default_value_str", models.CharField(max_length=255)),
                ("default_value_num", models.FloatField()),
                ("default_value_bool", models.BooleanField()),
                ("selection_options", models.CharField(max_length=1000)),
                ("selection_multiple", models.BooleanField(default=False)),
                (
                    "selection_multiple_n_min",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "selection_multiple_n_max",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "selection_default_options",
                    models.JSONField(blank=True, default=dict),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
