# Generated by Django 6.0 on 2025-12-18 12:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lx_django", "0007_intervention_interventiontypes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name", models.CharField(max_length=255)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "abbreviation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "type_names",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UnitType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name", models.CharField(max_length=255)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameModel(
            old_name="ClassificationTypes",
            new_name="ClassificationType",
        ),
        migrations.RenameModel(
            old_name="InterventionTypes",
            new_name="InterventionType",
        ),
    ]
