# Generated by Django 6.0 on 2025-12-18 13:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lx_django", "0008_unit_unittype_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name", models.CharField(max_length=255)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "classification_names",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                (
                    "type_names",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                (
                    "intervention_names",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FindingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name", models.CharField(max_length=255)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
