# Generated by Django 6.0 on 2025-12-18 14:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lx_django", "0011_examination_examinationtype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Citation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name", models.CharField(max_length=255)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("citation_key", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=1024)),
                ("abstract", models.CharField(blank=True, max_length=5000, null=True)),
                ("authors", models.CharField(blank=True, max_length=2000)),
                ("publication_year", models.IntegerField(blank=True, null=True)),
                (
                    "publication_month",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("journal", models.CharField(blank=True, max_length=255, null=True)),
                ("publisher", models.CharField(blank=True, max_length=255, null=True)),
                ("volume", models.CharField(blank=True, max_length=50, null=True)),
                ("issue", models.CharField(blank=True, max_length=50, null=True)),
                ("pages", models.CharField(blank=True, max_length=50, null=True)),
                ("doi", models.CharField(blank=True, max_length=255, null=True)),
                ("url", models.CharField(blank=True, max_length=1024, null=True)),
                ("entry_type", models.CharField(blank=True, max_length=100, null=True)),
                ("language", models.CharField(blank=True, max_length=50, null=True)),
                ("keywords", models.CharField(blank=True, max_length=2000)),
                ("identifiers", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
