from __future__ import annotations

from importlib import import_module
from typing import Any

_REPORT_TEMPLATE_EXPORTS = {
    "ReportTemplate",
    "ReportTemplateDataDict",
    "ReportTemplateGraph",
    "ReportTemplateGraphDataDict",
    "ReportTemplateGraphNode",
    "ReportTemplateGraphNodeDataDict",
    "ReportTemplateGraphEdge",
    "ReportTemplateGraphEdgeDataDict",
    "ReportTemplateStructureIssue",
    "ReportTemplateStructureIssueDataDict",
    "ReportTemplateStructureValidationResult",
    "ReportTemplateStructureValidationResultDataDict",
    "ReportTemplateSection",
    "ReportTemplateSectionDataDict",
    "ReportFinding",
    "ReportFindingDataDict",
    "FindingsValidator",
    "FindingsValidatorDataDict",
    "FindingsValidatorExecutionDataDict",
    "ExaminationValidator",
    "ExaminationValidatorDataDict",
    "ExaminationValidatorDependencyStatusDataDict",
    "ExaminationValidatorExecutionDataDict",
    "ReportTemplateRuntimeValidationResultDataDict",
    "RuntimeValidationIssueDataDict",
    "LookupInitRequest",
    "LookupInitRequestDataDict",
    "LookupPartsPatchRequest",
    "LookupPartsPatchRequestDataDict",
    "LookupPartsResponse",
    "LookupRecomputeResponse",
    "LookupRecomputeResponseDataDict",
    "LookupState",
    "LookupStateDataDict",
    "normalize_lookup_keys",
    "validate_lookup_state",
    "validate_lookup_parts_response",
    "validate_lookup_updates",
    "build_lookup_recompute_response",
    "evaluate_findings_validator_runtime",
    "evaluate_report_template_validators_runtime",
    "build_report_template_graph",
    "validate_report_template_structure",
    "validate_report_template_knowledge_base",
}

_CONTRACT_EXPORTS = {
    "CoreConceptBase",
    "ClassificationCore",
    "ClassificationChoiceCore",
    "ClassificationChoiceDescriptorCore",
    "ExaminationCore",
    "FindingCore",
    "FindingTypeCore",
    "IndicationCore",
    "IndicationTypeCore",
    "InterventionCore",
    "InterventionTypeCore",
    "UnitCore",
    "UnitTypeCore",
    "InformationSourceCore",
    "InformationSourceTypeCore",
    "CitationCore",
    "CoreConceptCollection",
    "record_to_core_concept",
    "records_to_core_concepts",
    "core_concept_to_storage",
    "kb_to_core_concepts_payload",
    "canonical_payload_to_storage",
}


def __getattr__(name: str) -> Any:
    if name in _REPORT_TEMPLATE_EXPORTS:
        module = import_module("lx_dtypes.models.knowledge_base.report_template")
        return getattr(module, name)

    if name in _CONTRACT_EXPORTS:
        module = import_module("lx_dtypes.models.contracts")
        return getattr(module, name)

    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    "ReportTemplate",
    "ReportTemplateDataDict",
    "ReportTemplateGraph",
    "ReportTemplateGraphDataDict",
    "ReportTemplateGraphNode",
    "ReportTemplateGraphNodeDataDict",
    "ReportTemplateGraphEdge",
    "ReportTemplateGraphEdgeDataDict",
    "ReportTemplateStructureIssue",
    "ReportTemplateStructureIssueDataDict",
    "ReportTemplateStructureValidationResult",
    "ReportTemplateStructureValidationResultDataDict",
    "ReportTemplateSection",
    "ReportTemplateSectionDataDict",
    "ReportFinding",
    "ReportFindingDataDict",
    "FindingsValidator",
    "FindingsValidatorDataDict",
    "FindingsValidatorExecutionDataDict",
    "ExaminationValidator",
    "ExaminationValidatorDataDict",
    "ExaminationValidatorDependencyStatusDataDict",
    "ExaminationValidatorExecutionDataDict",
    "ReportTemplateRuntimeValidationResultDataDict",
    "RuntimeValidationIssueDataDict",
    "LookupInitRequest",
    "LookupInitRequestDataDict",
    "LookupPartsPatchRequest",
    "LookupPartsPatchRequestDataDict",
    "LookupPartsResponse",
    "LookupRecomputeResponse",
    "LookupRecomputeResponseDataDict",
    "LookupState",
    "LookupStateDataDict",
    "normalize_lookup_keys",
    "validate_lookup_state",
    "validate_lookup_parts_response",
    "validate_lookup_updates",
    "build_lookup_recompute_response",
    "evaluate_findings_validator_runtime",
    "evaluate_report_template_validators_runtime",
    "build_report_template_graph",
    "validate_report_template_structure",
    "validate_report_template_knowledge_base",
    "CoreConceptBase",
    "ClassificationCore",
    "ClassificationChoiceCore",
    "ClassificationChoiceDescriptorCore",
    "ExaminationCore",
    "FindingCore",
    "FindingTypeCore",
    "IndicationCore",
    "IndicationTypeCore",
    "InterventionCore",
    "InterventionTypeCore",
    "UnitCore",
    "UnitTypeCore",
    "InformationSourceCore",
    "InformationSourceTypeCore",
    "CitationCore",
    "CoreConceptCollection",
    "record_to_core_concept",
    "records_to_core_concepts",
    "core_concept_to_storage",
    "kb_to_core_concepts_payload",
    "canonical_payload_to_storage",
]
