"""Public contracts, loaded on demand without importing unrelated domains."""

from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from .adapters import (
        CoreConceptModel,
        CoreConceptName,
        canonical_payload_to_storage,
        core_concept_to_storage,
        kb_to_core_concepts_payload,
        record_to_core_concept,
        records_to_core_concepts,
    )
    from .ai_dataset import (
        AIDataSetActiveLearningCandidateContract,
        AIDataSetActiveLearningConfigContract,
        AIDataSetActiveLearningSelectionContract,
        AIDataSetAttachmentResultContract,
        AIDataSetAttachVideoContract,
        AIDataSetCreateContract,
        AIDataSetScoredActiveLearningCandidateContract,
        AIDataSetStandardExportScopeContract,
    )
    from .ai_model import (
        AiModelSerializerInputPayload,
        AiModelSerializerOutputPayload,
        validate_ai_model_serializer_input_payload,
        validate_ai_model_serializer_output_payload,
    )
    from .aidataset_frame_buckets import (
        AIDataSetFrameBucketCount,
        AIDataSetFrameBucketDistribution,
        AIDataSetFrameBucketSummary,
        AIDataSetLabelDistributionEntry,
        AIDataSetLabelFrameBucketCount,
        AIDataSetTargetFrameBucket,
    )
    from .anonymization_metrics import (
        AnonymizationFieldQualityPayload,
        AnonymizationMetricsFiltersPayload,
        AnonymizationMetricsPayload,
        AnonymizationMetricsQueryBoundsPayload,
        AnonymizationPhiRegionMetricsPayload,
        AnonymizationQualityMetricsPayload,
        AnonymizationWorkflowMetricsPayload,
    )
    from .anonymization_quality import (
        AnonymizationQualityPayload,
        AnonymizationQualityResult,
        AnonymizationQualitySummary,
        QualityEvaluationStatus,
        SensitiveMetaHandlingPolicy,
    )
    from .application_settings import (
        ApplicationSettingsBackupSourcePayload,
        ApplicationSettingsBackupStatusPayload,
        ApplicationSettingsDataSetEntryPayload,
        ApplicationSettingsDeploymentProfilePayload,
        ApplicationSettingsDeploymentRole,
        ApplicationSettingsPayload,
    )
    from .authz import (
        KeycloakClaimsPayload,
        KeycloakRoleContainerPayload,
        validate_keycloak_claims,
    )
    from .case_resolution import (
        CaseResolutionNewPatient,
        CaseResolutionRequest,
        CaseResolutionResponse,
        ValidationError,
    )
    from .codemod_rename import CodemodRenameMapPayload, validate_codemod_rename_map
    from .contraindication import ContraindicationCore
    from .core_concepts import (
        CitationCore,
        ClassificationChoiceCore,
        ClassificationChoiceDescriptorCore,
        ClassificationCore,
        ClassificationTypeCore,
        CoreConceptBase,
        CoreConceptCollection,
        ExaminationCore,
        FindingCore,
        FindingTypeCore,
        IndicationCore,
        IndicationTypeCore,
        InformationSourceCore,
        InformationSourceTypeCore,
        InterventionCore,
        InterventionTypeCore,
        UnitCore,
        UnitTypeCore,
    )
    from .django_settings import (
        DjangoBeatScheduleEntryPayload,
        DjangoBeatScheduleOptionsPayload,
        DjangoCacheConfigPayload,
        DjangoCacheSettingsPayload,
        DjangoRestFrameworkSettingsPayload,
        DjangoTemplateConfigPayload,
        DjangoTemplateOptionsPayload,
    )
    from .document_type import DocumentType
    from .dtypes_record_persistence import (
        DescriptorValue,
        DtypesRecordClassificationChoiceDescriptorPayload,
        DtypesRecordClassificationChoicePayload,
        DtypesRecordClassificationGroupPayload,
        DtypesRecordFindingPayload,
        DtypesRecordIndicationClassificationDescriptorPayload,
        DtypesRecordIndicationClassificationPayload,
        DtypesRecordIndicationPayload,
        DtypesRecordInterventionGroupPayload,
        DtypesRecordInterventionPayload,
        DtypesRecordPersistencePayload,
        dump_dtypes_record_persistence_payload,
        parse_dtypes_record_persistence_payload,
    )
    from .endoscopy_processor import (
        EndoscopeImageRoiCore,
        EndoscopyProcessorCore,
        RoiBoxCore,
    )
    from .event import (
        EventClassificationChoiceCore,
        EventClassificationCore,
        EventCore,
    )
    from .examination_indication import (
        ExaminationIndicationClassificationChoiceCore,
        ExaminationIndicationClassificationCore,
        ExaminationIndicationCore,
    )
    from .examination_time import ExaminationTimeCore, ExaminationTimeTypeCore
    from .examination_type import ExaminationTypeCore
    from .export_ready import (
        ReadyForExportResult,
        VideoReadyForExportData,
        VideoReadyForExportPayload,
        dump_video_ready_for_export_payload,
        validate_video_ready_for_export_payload,
    )
    from .fhir_clinical import (
        ClinicalFhirResource,
        FhirClinicalBundle,
        FhirClinicalBundleEntry,
        FhirCodeableConcept,
        FhirCoding,
        FhirCondition,
        FhirDiagnosticReport,
        FhirObservation,
        FhirObservationComponent,
        FhirPatient,
        FhirQuantity,
        FhirReference,
        ResolvedDiagnosticReport,
    )
    from .finding_classification import (
        FindingClassificationChoiceCore,
        FindingClassificationCore,
        FindingClassificationTypeCore,
    )
    from .finding_intervention import (
        FindingInterventionCore,
        FindingInterventionTypeCore,
    )
    from .frame_annotation import (
        FrameAnnotationRandomTaskResponsePayload,
        FrameAnnotationSkipResponsePayload,
    )
    from .hub_media_envelope import (
        HubMediaEnvelopeMetadata,
        HubMediaEnvelopeReceipt,
        validate_hub_media_receipt_matches_envelope,
    )
    from .hub_transfer import (
        HubTransferReportTransferPayload,
        HubTransferSegmentProvenancePayload,
        HubTransferVideoSegmentPayload,
        HubTransferVideoTransferPayload,
        validate_hub_transfer_report_payload,
        validate_hub_transfer_video_payload,
    )
    from .huggingface_model_meta import (
        HuggingFaceModelMetaCommandData,
        HuggingFaceModelMetaCommandPayload,
        HuggingFaceModelMetaCommandValue,
        huggingface_model_meta_command_data_from_mapping,
        validate_huggingface_model_meta_command_payload,
    )
    from .knowledge_base import (
        KnowledgeBaseContract,
        KnowledgeBaseIdentity,
        validate_optional_knowledge_base_identity,
    )
    from .knowledge_base_graph import (
        KNOWLEDGE_BASE_GRAPH_CONTRACT_VERSION,
        ExaminationReportingContext,
        KnowledgeBaseGraphEdge,
        KnowledgeBaseGraphNodeRef,
        KnowledgeBaseGraphResolver,
        KnowledgeBaseGraphSnapshot,
        ReportTemplateGraphProjection,
        build_examination_reporting_context,
        build_knowledge_base_graph_snapshot,
    )
    from .lab_value import (
        LabValueNormalRangeData,
        LabValueNormalRangePayload,
    )
    from .legacy_data_import import (
        LegacyDataImportCommandOptionsPayload,
        LegacyExaminationIdValue,
        LegacyImageImportRowPayload,
        LegacyImportManifestData,
        LegacyImportManifestPayload,
        LegacyIntOrNull,
        LegacyTextOrNull,
        dump_legacy_import_manifest,
    )
    from .legacy_data_import import (
        NullValue as LegacyNullValue,
    )
    from .lx_anonymizer_performance import (
        LX_ANONYMIZER_PERFORMANCE_CSV_FIELDNAMES,
        LxAnonymizerDurationStatsPayload,
        LxAnonymizerPerformanceCsvCell,
        LxAnonymizerPerformanceCsvRow,
        LxAnonymizerPerformanceMediaType,
        LxAnonymizerPerformancePayload,
        LxAnonymizerPerformanceRunPayload,
        LxAnonymizerPerformanceSummaryPayload,
        dump_lx_anonymizer_performance_run_csv_row,
    )
    from .maintenance_repair import (
        SensitiveMetaPatientRepairCreatePayload,
        SensitiveMetaPatientRepairData,
        SensitiveMetaPatientRepairUpdatePayload,
        SensitiveMetaRepairValue,
        VideoPathRepairFileIndex,
        VideoPathRepairFileInfoPayload,
        dump_sensitive_meta_patient_repair_create_payload,
        dump_sensitive_meta_patient_repair_update_payload,
    )
    from .management_command import (
        FrameSegmentReconciliationTrack,
        ModelInputCommandOptionsPayload,
        ModelTrainingResultPayload,
        ReapQuarantineCommandOptionsPayload,
        ReapUploadJobSourcesCommandOptionsPayload,
        ReconcileFrameSegmentAnnotationsCommandOptionsPayload,
        ReconcileMediaIntegrityCommandOptionsPayload,
        ReconcileSegmentValidationStateCommandOptionsPayload,
        ReconcileVideoFormatsCommandOptionsPayload,
        RefreshAuditLedgerIntegrityCommandOptionsPayload,
        RegisterAiModelCommandOptionsPayload,
        RegisterAiModelMetaPayload,
        RuntimeStorageContractPayload,
        SetupEndoregDbCommandOptionsPayload,
        ShowUrlsCommandOptionsPayload,
        ShowUrlsRoutePayload,
        ShowUrlsRoutesPayload,
        StorageManagementCommandOptionsPayload,
        StorageManagementInfoPayload,
        TrainImageMultilabelModelCommandOptionsPayload,
        TrainPhiRegionDetectorCommandOptionsPayload,
        TranscodeVideoCommandOptionsPayload,
        TranscodeVideoQualityMode,
        ValidateRuntimeStorageContractCommandOptionsPayload,
        ValidateVideoFilesCommandOptionsPayload,
        ValidateVideoFileStatus,
        ValidateVideoFileStatusPayload,
        VerboseManagementCommandOptionsPayload,
        validate_model_training_result,
    )
    from .media_streaming import (
        ByteRange,
        FfmpegActiveStreamThrottleState,
        FfmpegStreamInfo,
        FfmpegStreamProbeEntry,
        FfmpegStreamThrottleState,
        FfmpegStreamThrottleStatePayload,
        MediaOperationLeaseSummary,
        MediaOperationLeaseSummaryPayload,
        MediaStreamDisposition,
        MediaStreamFileKind,
        StreamThrottleMode,
        dump_ffmpeg_stream_throttle_state,
        dump_media_operation_lease_summary,
        validate_ffmpeg_stream_info,
    )
    from .migrate_data_dir import (
        MigrateDataDirCommandOptionsPayload,
        MigrateDataDirManifestData,
        MigrateDataDirManifestEntryData,
        MigrateDataDirManifestEntryPayload,
        MigrateDataDirManifestPayload,
        MigrateDataDirManifestValue,
        MigrateDataDirNull,
    )
    from .nginx_accel import NginxAccelResponseHeadersPayload
    from .patient_examination import PatientExaminationPatientDataPayload
    from .patient_examination_report import (
        PatientExaminationReportMakeReportData,
        PatientExaminationReportMakeReportPayload,
        PatientExaminationReportSubmissionData,
        PatientExaminationReportSubmissionPayload,
        PatientReportIdentityData,
        PatientReportIdentityPayload,
        ReportExportFrameDetailData,
        ReportJsonObject,
        ReportJsonValue,
        ReportPersistedArtifactsData,
        ReportPersistedArtifactsPayload,
        ReportSegmentFrameSelectionData,
        ReportSegmentFrameSelectionPayload,
        ReportSegmentSelectionMap,
        ReportStatus,
        SegmentAttachedFindingData,
        SegmentFrameControlsData,
        SegmentFramePreviewData,
        SegmentFrameSelectionAction,
        SegmentFrameSelectorItemData,
        SegmentFrameSelectorPatchData,
        SegmentFrameSelectorPatchPayload,
        SegmentFrameSelectorQueryData,
        SegmentFrameSelectorQueryPayload,
        SegmentFrameSelectorResponseData,
        SegmentSelectionMetaData,
        dump_make_report_payload,
        dump_persisted_artifacts_payload,
        dump_report_submission_payload,
        dump_segment_frame_selection_payload,
        dump_selector_patch_payload,
        dump_selector_query_payload,
        report_json_safe,
        report_json_safe_dict,
        validate_segment_selection_map,
    )
    from .patient_finding_classification import (
        PatientFindingClassificationCreateData,
        PatientFindingClassificationCreatePayload,
        dump_patient_finding_classification_create_payload,
        validate_patient_finding_classification_create_payload,
    )
    from .patient_finding_classification_runtime import (
        PatientFindingClassificationNumericalDescriptorPayload,
        PatientFindingClassificationNumericalDescriptorsData,
        PatientFindingClassificationNumericalDescriptorsPayload,
        PatientFindingClassificationSubcategoriesData,
        PatientFindingClassificationSubcategoriesPayload,
        PatientFindingClassificationSubcategoryPayload,
    )
    from .pdf_file import (
        PdfFileContextPayload,
        PdfFileIdentityPayload,
        PdfFileMetaJsonObject,
        PdfFileMetaJsonValue,
        PdfFilePayload,
        PdfFileProcessingStatePayload,
        PdfFileStoragePayload,
    )
    from .pdf_meta import PdfMetaPayload, PdfTypeSummaryPayload
    from .pdf_redaction import (
        PdfRedactionBox,
        PdfRedactionManifest,
        PdfRedactionPage,
        PdfRedactionRequest,
        PdfRedactionResponse,
    )
    from .pseudonymization import (
        KAnonymityResult,
        KPseudonymizationResult,
        QuasiIdentifierField,
        QuasiIdentifierSubset,
    )
    from .report import (
        Report,
        ReportMetaJsonObject,
        ReportMetaJsonValue,
        ReportPayload,
        ReportVersion,
        SerializedReport,
    )
    from .report_anonymization import (
        REPORT_ANONYMIZATION_CONTRACT_VERSION,
        ReportAnonymizationContractVersion,
        ReportAnonymizationErrorCode,
        ReportAnonymizationFailure,
        ReportAnonymizationOptions,
        ReportAnonymizationPhase,
        ReportAnonymizationProvenance,
        ReportAnonymizationRequest,
        ReportAnonymizationResult,
        ReportAnonymizationWarning,
        ReportAnonymizationWarningCode,
        ReportArtifactValidation,
    )
    from .report_context import ReportContext
    from .report_draft import (
        REPORT_DRAFT_SCHEMA_VERSION,
        PatientExaminationReportDraft,
        ReportDraftTemplateIdentity,
        dump_patient_examination_report_draft,
    )
    from .study_cohort import (
        StudyCohortCaseRow,
        StudyCohortExaminationRow,
        StudyCohortMediaRow,
        StudyCohortReportRow,
    )
    from .terminology_catalog import (
        ExaminationCatalogDTO,
        IndicationCatalogDTO,
        LocalizedCatalogItem,
    )
    from .transfer_validation import (
        TransferValidationFailureLogPayload,
        TransferValidationLogScalar,
        TransferValidationLogValue,
        dump_transfer_validation_failure_log_payload,
    )
    from .upload import (
        UploadApiRequestData,
        UploadApiRequestPayload,
        upload_api_request_data_from_mapping,
        validate_upload_api_request_payload,
    )
    from .video_ai_labels import (
        VideoAiHuggingFaceModelPayload,
        VideoAiJsonObject,
        VideoAiLabelMutationResponsePayload,
        VideoAiLabelNamePayload,
        VideoAiLabelPayload,
        VideoAiLabelRenamePayload,
        VideoAiLabelSetPayload,
        VideoAiPredictionJobPayload,
        VideoAiPredictionModelListPayload,
        VideoAiPredictionModelMetaPayload,
        VideoAiRerunPredictionRequestPayload,
        VideoAiRerunPredictionResponsePayload,
        validate_video_ai_label_name_payload,
        validate_video_ai_label_rename_payload,
        validate_video_ai_rerun_prediction_request,
        video_ai_json_safe_dict,
    )
    from .video_correction import (
        VideoCorrectionApplyMaskPayload,
        VideoCorrectionApplyMaskResponsePayload,
        VideoCorrectionErrorPayload,
        VideoCorrectionFrameRemovalPayload,
        VideoCorrectionMaskType,
        VideoCorrectionProcessingMethod,
        VideoCorrectionRemoveFramesResponsePayload,
        VideoCorrectionRoiData,
        VideoCorrectionRoiPayload,
        VideoCorrectionSegmentUpdateData,
        VideoCorrectionSegmentUpdatePayload,
        dump_video_correction_roi_payload,
        dump_video_correction_segment_update_payload,
        parse_video_correction_frame_ranges,
        validate_video_correction_apply_mask_payload,
        validate_video_correction_frame_removal_payload,
    )
    from .video_examination import (
        VideoExaminationCreateData,
        VideoExaminationCreatePayload,
        VideoExaminationFindingData,
        VideoExaminationFindingPayload,
        VideoExaminationListQueryData,
        VideoExaminationListQueryPayload,
        VideoExaminationPathPayload,
        VideoExaminationUpdateData,
        VideoExaminationUpdatePayload,
        dump_video_examination_create_payload,
        dump_video_examination_finding_payload,
        dump_video_examination_list_query_payload,
        dump_video_examination_update_payload,
        validate_video_examination_list_query,
        validate_video_examination_path_payload,
    )
    from .video_export import (
        VideoAnnotationExportConfigUpdateData,
        VideoAnnotationExportErrorPayload,
        VideoAnnotationExportFormat,
        VideoAnnotationExportRequestPayload,
        VideoAnnotationExportResultPayload,
        dump_video_annotation_export_update_payload,
    )
    from .video_file import (
        FrameSourceMode,
        VideoFileIdentityPayload,
        VideoFileMetaJsonObject,
        VideoFileMetaJsonValue,
        VideoFilePayload,
        VideoFileStoragePayload,
        VideoFileTechnicalMetadataPayload,
    )
    from .video_frame_annotations import (
        FrameAnnotationBulkEnvelopeData,
        FrameAnnotationBulkEnvelopePayload,
        FrameAnnotationBulkItemData,
        FrameAnnotationBulkItemPayload,
        FrameAnnotationPayloadMapping,
        FrameAnnotationSkipPayload,
        FrameBoxAnnotationBulkEnvelopeData,
        FrameBoxAnnotationBulkEnvelopePayload,
        FrameBoxAnnotationBulkItemData,
        FrameBoxAnnotationBulkItemPayload,
        dump_frame_annotation_bulk_item,
        dump_frame_box_annotation_bulk_item,
    )
    from .video_frame_box_annotations import (
        VideoFrameBoxAnnotationListResponsePayload,
        VideoFrameBoxAnnotationMutationResponsePayload,
        VideoFrameBoxAnnotationRequestPayload,
        VideoFrameBoxJsonObject,
        validate_video_frame_box_annotation_request,
        video_frame_box_json_safe_dict,
    )
    from .video_frame_export import (
        VideoFrameAnnotationExportConfigPayload,
        VideoFrameAnnotationExportFormat,
        YamlScalar,
        YamlValue,
        export_config,
        export_result,
        load_video_frame_annotation_export_config,
        validate_video_frame_annotation_export_config,
    )
    from .video_reimport import (
        VIDEO_REIMPORT_HISTORY_KIND,
        VIDEO_REIMPORT_OPERATION,
        JsonObject,
        JsonValue,
        VideoReimportApiResponseData,
        VideoReimportApiResponsePayload,
        VideoReimportApiStatus,
        VideoReimportDispatchResult,
        VideoReimportDispatchStatus,
        VideoReimportErrorType,
        VideoReimportHistoryConfig,
        VideoReimportJobMode,
        VideoReimportJsonValue,
        VideoReimportOperation,
        VideoReimportPredictionRefreshPayload,
        VideoReimportPredictionRefreshStatus,
        VideoReimportRequestData,
        VideoReimportRequestPayload,
        VideoReimportStatus,
        dump_video_reimport_api_response,
        dump_video_reimport_request_payload,
        validate_video_reimport_request_payload,
        video_reimport_json_safe,
        video_reimport_json_safe_dict,
    )
    from .video_segment_validation import (
        OutsideFrameBlackeningHistoryConfigData,
        OutsideFrameBlackeningHistoryConfigPayload,
        PostValidationRebuildSummaryData,
        PostValidationRebuildSummaryPayload,
        VideoSegmentValidationNull,
        VideoSegmentValidationText,
    )
    from .video_segments import (
        SegmentAnnotationEnsurePayload,
        SegmentAnnotationInput,
        SegmentAnnotationMetadataInput,
        SegmentBlackenOutsidePayload,
        SegmentBulkValidationItem,
        SegmentBulkValidationPayload,
        SegmentCrudPayload,
        SegmentListQuery,
        SegmentPredictionImportItem,
        SegmentPredictionImportPayload,
        SegmentValidationPayload,
        SegmentValidationStatusPayload,
        VideoSegmentsPayload,
        VideoSegmentsPayloadDict,
        parse_segment_annotation_input,
        validate_segment_annotation_ensure_payload,
        validate_segment_blacken_outside_payload,
        validate_segment_bulk_validation_payload,
        validate_segment_crud_payload,
        validate_segment_list_query,
        validate_segment_prediction_import_payload,
        validate_segment_validation_payload,
        validate_segment_validation_status_payload,
        validate_video_segments_payload,
    )
    from .video_temporal_inference import (
        TemporalInferenceDispatchResult,
        TemporalInferenceHistoryConfigPayload,
        TemporalInferenceHistoryResultPayload,
        parse_temporal_inference_history_config_payload,
        parse_temporal_inference_history_result_payload,
    )
    from .video_text_metadata import VideoTextMetaPayload, VideoTextMetaValue


_EXPORT_MODULES: dict[str, str] = {
    "CoreConceptModel": "adapters",
    "CoreConceptName": "adapters",
    "canonical_payload_to_storage": "adapters",
    "core_concept_to_storage": "adapters",
    "kb_to_core_concepts_payload": "adapters",
    "record_to_core_concept": "adapters",
    "records_to_core_concepts": "adapters",
    "AIDataSetActiveLearningCandidateContract": "ai_dataset",
    "AIDataSetActiveLearningConfigContract": "ai_dataset",
    "AIDataSetActiveLearningSelectionContract": "ai_dataset",
    "AIDataSetAttachmentResultContract": "ai_dataset",
    "AIDataSetAttachVideoContract": "ai_dataset",
    "AIDataSetCreateContract": "ai_dataset",
    "AIDataSetScoredActiveLearningCandidateContract": "ai_dataset",
    "AIDataSetStandardExportScopeContract": "ai_dataset",
    "AiModelSerializerInputPayload": "ai_model",
    "AiModelSerializerOutputPayload": "ai_model",
    "validate_ai_model_serializer_input_payload": "ai_model",
    "validate_ai_model_serializer_output_payload": "ai_model",
    "AIDataSetFrameBucketCount": "aidataset_frame_buckets",
    "AIDataSetFrameBucketDistribution": "aidataset_frame_buckets",
    "AIDataSetFrameBucketSummary": "aidataset_frame_buckets",
    "AIDataSetLabelDistributionEntry": "aidataset_frame_buckets",
    "AIDataSetLabelFrameBucketCount": "aidataset_frame_buckets",
    "AIDataSetTargetFrameBucket": "aidataset_frame_buckets",
    "AnonymizationFieldQualityPayload": "anonymization_metrics",
    "AnonymizationMetricsFiltersPayload": "anonymization_metrics",
    "AnonymizationMetricsPayload": "anonymization_metrics",
    "AnonymizationMetricsQueryBoundsPayload": "anonymization_metrics",
    "AnonymizationPhiRegionMetricsPayload": "anonymization_metrics",
    "AnonymizationQualityMetricsPayload": "anonymization_metrics",
    "AnonymizationWorkflowMetricsPayload": "anonymization_metrics",
    "AnonymizationQualityPayload": "anonymization_quality",
    "AnonymizationQualityResult": "anonymization_quality",
    "AnonymizationQualitySummary": "anonymization_quality",
    "QualityEvaluationStatus": "anonymization_quality",
    "SensitiveMetaHandlingPolicy": "anonymization_quality",
    "ApplicationSettingsBackupSourcePayload": "application_settings",
    "ApplicationSettingsBackupStatusPayload": "application_settings",
    "ApplicationSettingsDataSetEntryPayload": "application_settings",
    "ApplicationSettingsDeploymentProfilePayload": "application_settings",
    "ApplicationSettingsDeploymentRole": "application_settings",
    "ApplicationSettingsPayload": "application_settings",
    "KeycloakClaimsPayload": "authz",
    "KeycloakRoleContainerPayload": "authz",
    "validate_keycloak_claims": "authz",
    "CaseResolutionNewPatient": "case_resolution",
    "CaseResolutionRequest": "case_resolution",
    "CaseResolutionResponse": "case_resolution",
    "ValidationError": "case_resolution",
    "CodemodRenameMapPayload": "codemod_rename",
    "validate_codemod_rename_map": "codemod_rename",
    "ContraindicationCore": "contraindication",
    "CitationCore": "core_concepts",
    "ClassificationChoiceCore": "core_concepts",
    "ClassificationChoiceDescriptorCore": "core_concepts",
    "ClassificationCore": "core_concepts",
    "ClassificationTypeCore": "core_concepts",
    "CoreConceptBase": "core_concepts",
    "CoreConceptCollection": "core_concepts",
    "ExaminationCore": "core_concepts",
    "FindingCore": "core_concepts",
    "FindingTypeCore": "core_concepts",
    "IndicationCore": "core_concepts",
    "IndicationTypeCore": "core_concepts",
    "InformationSourceCore": "core_concepts",
    "InformationSourceTypeCore": "core_concepts",
    "InterventionCore": "core_concepts",
    "InterventionTypeCore": "core_concepts",
    "UnitCore": "core_concepts",
    "UnitTypeCore": "core_concepts",
    "DjangoBeatScheduleEntryPayload": "django_settings",
    "DjangoBeatScheduleOptionsPayload": "django_settings",
    "DjangoCacheConfigPayload": "django_settings",
    "DjangoCacheSettingsPayload": "django_settings",
    "DjangoRestFrameworkSettingsPayload": "django_settings",
    "DjangoTemplateConfigPayload": "django_settings",
    "DjangoTemplateOptionsPayload": "django_settings",
    "DocumentType": "document_type",
    "DescriptorValue": "dtypes_record_persistence",
    "DtypesRecordClassificationChoiceDescriptorPayload": "dtypes_record_persistence",
    "DtypesRecordClassificationChoicePayload": "dtypes_record_persistence",
    "DtypesRecordClassificationGroupPayload": "dtypes_record_persistence",
    "DtypesRecordFindingPayload": "dtypes_record_persistence",
    "DtypesRecordIndicationClassificationDescriptorPayload": "dtypes_record_persistence",
    "DtypesRecordIndicationClassificationPayload": "dtypes_record_persistence",
    "DtypesRecordIndicationPayload": "dtypes_record_persistence",
    "DtypesRecordInterventionGroupPayload": "dtypes_record_persistence",
    "DtypesRecordInterventionPayload": "dtypes_record_persistence",
    "DtypesRecordPersistencePayload": "dtypes_record_persistence",
    "dump_dtypes_record_persistence_payload": "dtypes_record_persistence",
    "parse_dtypes_record_persistence_payload": "dtypes_record_persistence",
    "EndoscopeImageRoiCore": "endoscopy_processor",
    "EndoscopyProcessorCore": "endoscopy_processor",
    "RoiBoxCore": "endoscopy_processor",
    "EventClassificationChoiceCore": "event",
    "EventClassificationCore": "event",
    "EventCore": "event",
    "ExaminationIndicationClassificationChoiceCore": "examination_indication",
    "ExaminationIndicationClassificationCore": "examination_indication",
    "ExaminationIndicationCore": "examination_indication",
    "ExaminationTimeCore": "examination_time",
    "ExaminationTimeTypeCore": "examination_time",
    "ExaminationTypeCore": "examination_type",
    "ReadyForExportResult": "export_ready",
    "VideoReadyForExportData": "export_ready",
    "VideoReadyForExportPayload": "export_ready",
    "dump_video_ready_for_export_payload": "export_ready",
    "validate_video_ready_for_export_payload": "export_ready",
    "ClinicalFhirResource": "fhir_clinical",
    "FhirClinicalBundle": "fhir_clinical",
    "FhirClinicalBundleEntry": "fhir_clinical",
    "FhirCodeableConcept": "fhir_clinical",
    "FhirCoding": "fhir_clinical",
    "FhirCondition": "fhir_clinical",
    "FhirDiagnosticReport": "fhir_clinical",
    "FhirObservation": "fhir_clinical",
    "FhirObservationComponent": "fhir_clinical",
    "FhirPatient": "fhir_clinical",
    "FhirQuantity": "fhir_clinical",
    "FhirReference": "fhir_clinical",
    "ResolvedDiagnosticReport": "fhir_clinical",
    "FindingClassificationChoiceCore": "finding_classification",
    "FindingClassificationCore": "finding_classification",
    "FindingClassificationTypeCore": "finding_classification",
    "FindingInterventionCore": "finding_intervention",
    "FindingInterventionTypeCore": "finding_intervention",
    "FrameAnnotationRandomTaskResponsePayload": "frame_annotation",
    "FrameAnnotationSkipResponsePayload": "frame_annotation",
    "HubMediaEnvelopeMetadata": "hub_media_envelope",
    "HubMediaEnvelopeReceipt": "hub_media_envelope",
    "validate_hub_media_receipt_matches_envelope": "hub_media_envelope",
    "HubTransferReportTransferPayload": "hub_transfer",
    "HubTransferSegmentProvenancePayload": "hub_transfer",
    "HubTransferVideoSegmentPayload": "hub_transfer",
    "HubTransferVideoTransferPayload": "hub_transfer",
    "validate_hub_transfer_report_payload": "hub_transfer",
    "validate_hub_transfer_video_payload": "hub_transfer",
    "HuggingFaceModelMetaCommandData": "huggingface_model_meta",
    "HuggingFaceModelMetaCommandPayload": "huggingface_model_meta",
    "HuggingFaceModelMetaCommandValue": "huggingface_model_meta",
    "huggingface_model_meta_command_data_from_mapping": "huggingface_model_meta",
    "validate_huggingface_model_meta_command_payload": "huggingface_model_meta",
    "KnowledgeBaseContract": "knowledge_base",
    "KnowledgeBaseIdentity": "knowledge_base",
    "validate_optional_knowledge_base_identity": "knowledge_base",
    "KNOWLEDGE_BASE_GRAPH_CONTRACT_VERSION": "knowledge_base_graph",
    "ExaminationReportingContext": "knowledge_base_graph",
    "KnowledgeBaseGraphEdge": "knowledge_base_graph",
    "KnowledgeBaseGraphNodeRef": "knowledge_base_graph",
    "KnowledgeBaseGraphResolver": "knowledge_base_graph",
    "KnowledgeBaseGraphSnapshot": "knowledge_base_graph",
    "ReportTemplateGraphProjection": "knowledge_base_graph",
    "build_examination_reporting_context": "knowledge_base_graph",
    "build_knowledge_base_graph_snapshot": "knowledge_base_graph",
    "LabValueNormalRangeData": "lab_value",
    "LabValueNormalRangePayload": "lab_value",
    "LegacyDataImportCommandOptionsPayload": "legacy_data_import",
    "LegacyExaminationIdValue": "legacy_data_import",
    "LegacyImageImportRowPayload": "legacy_data_import",
    "LegacyImportManifestData": "legacy_data_import",
    "LegacyImportManifestPayload": "legacy_data_import",
    "LegacyIntOrNull": "legacy_data_import",
    "LegacyTextOrNull": "legacy_data_import",
    "dump_legacy_import_manifest": "legacy_data_import",
    "LegacyNullValue": "legacy_data_import",
    "LX_ANONYMIZER_PERFORMANCE_CSV_FIELDNAMES": "lx_anonymizer_performance",
    "LxAnonymizerDurationStatsPayload": "lx_anonymizer_performance",
    "LxAnonymizerPerformanceCsvCell": "lx_anonymizer_performance",
    "LxAnonymizerPerformanceCsvRow": "lx_anonymizer_performance",
    "LxAnonymizerPerformanceMediaType": "lx_anonymizer_performance",
    "LxAnonymizerPerformancePayload": "lx_anonymizer_performance",
    "LxAnonymizerPerformanceRunPayload": "lx_anonymizer_performance",
    "LxAnonymizerPerformanceSummaryPayload": "lx_anonymizer_performance",
    "dump_lx_anonymizer_performance_run_csv_row": "lx_anonymizer_performance",
    "SensitiveMetaPatientRepairCreatePayload": "maintenance_repair",
    "SensitiveMetaPatientRepairData": "maintenance_repair",
    "SensitiveMetaPatientRepairUpdatePayload": "maintenance_repair",
    "SensitiveMetaRepairValue": "maintenance_repair",
    "VideoPathRepairFileIndex": "maintenance_repair",
    "VideoPathRepairFileInfoPayload": "maintenance_repair",
    "dump_sensitive_meta_patient_repair_create_payload": "maintenance_repair",
    "dump_sensitive_meta_patient_repair_update_payload": "maintenance_repair",
    "FrameSegmentReconciliationTrack": "management_command",
    "ModelInputCommandOptionsPayload": "management_command",
    "ModelTrainingResultPayload": "management_command",
    "ReapQuarantineCommandOptionsPayload": "management_command",
    "ReapUploadJobSourcesCommandOptionsPayload": "management_command",
    "ReconcileFrameSegmentAnnotationsCommandOptionsPayload": "management_command",
    "ReconcileMediaIntegrityCommandOptionsPayload": "management_command",
    "ReconcileSegmentValidationStateCommandOptionsPayload": "management_command",
    "ReconcileVideoFormatsCommandOptionsPayload": "management_command",
    "RefreshAuditLedgerIntegrityCommandOptionsPayload": "management_command",
    "RegisterAiModelCommandOptionsPayload": "management_command",
    "RegisterAiModelMetaPayload": "management_command",
    "RuntimeStorageContractPayload": "management_command",
    "SetupEndoregDbCommandOptionsPayload": "management_command",
    "ShowUrlsCommandOptionsPayload": "management_command",
    "ShowUrlsRoutePayload": "management_command",
    "ShowUrlsRoutesPayload": "management_command",
    "StorageManagementCommandOptionsPayload": "management_command",
    "StorageManagementInfoPayload": "management_command",
    "TrainImageMultilabelModelCommandOptionsPayload": "management_command",
    "TrainPhiRegionDetectorCommandOptionsPayload": "management_command",
    "TranscodeVideoCommandOptionsPayload": "management_command",
    "TranscodeVideoQualityMode": "management_command",
    "ValidateRuntimeStorageContractCommandOptionsPayload": "management_command",
    "ValidateVideoFilesCommandOptionsPayload": "management_command",
    "ValidateVideoFileStatus": "management_command",
    "ValidateVideoFileStatusPayload": "management_command",
    "VerboseManagementCommandOptionsPayload": "management_command",
    "validate_model_training_result": "management_command",
    "ByteRange": "media_streaming",
    "FfmpegActiveStreamThrottleState": "media_streaming",
    "FfmpegStreamInfo": "media_streaming",
    "FfmpegStreamProbeEntry": "media_streaming",
    "FfmpegStreamThrottleState": "media_streaming",
    "FfmpegStreamThrottleStatePayload": "media_streaming",
    "MediaOperationLeaseSummary": "media_streaming",
    "MediaOperationLeaseSummaryPayload": "media_streaming",
    "MediaStreamDisposition": "media_streaming",
    "MediaStreamFileKind": "media_streaming",
    "StreamThrottleMode": "media_streaming",
    "dump_ffmpeg_stream_throttle_state": "media_streaming",
    "dump_media_operation_lease_summary": "media_streaming",
    "validate_ffmpeg_stream_info": "media_streaming",
    "MigrateDataDirCommandOptionsPayload": "migrate_data_dir",
    "MigrateDataDirManifestData": "migrate_data_dir",
    "MigrateDataDirManifestEntryData": "migrate_data_dir",
    "MigrateDataDirManifestEntryPayload": "migrate_data_dir",
    "MigrateDataDirManifestPayload": "migrate_data_dir",
    "MigrateDataDirManifestValue": "migrate_data_dir",
    "MigrateDataDirNull": "migrate_data_dir",
    "NginxAccelResponseHeadersPayload": "nginx_accel",
    "PatientExaminationPatientDataPayload": "patient_examination",
    "PatientExaminationReportMakeReportData": "patient_examination_report",
    "PatientExaminationReportMakeReportPayload": "patient_examination_report",
    "PatientExaminationReportSubmissionData": "patient_examination_report",
    "PatientExaminationReportSubmissionPayload": "patient_examination_report",
    "PatientReportIdentityData": "patient_examination_report",
    "PatientReportIdentityPayload": "patient_examination_report",
    "ReportExportFrameDetailData": "patient_examination_report",
    "ReportJsonObject": "patient_examination_report",
    "ReportJsonValue": "patient_examination_report",
    "ReportPersistedArtifactsData": "patient_examination_report",
    "ReportPersistedArtifactsPayload": "patient_examination_report",
    "ReportSegmentFrameSelectionData": "patient_examination_report",
    "ReportSegmentFrameSelectionPayload": "patient_examination_report",
    "ReportSegmentSelectionMap": "patient_examination_report",
    "ReportStatus": "patient_examination_report",
    "SegmentAttachedFindingData": "patient_examination_report",
    "SegmentFrameControlsData": "patient_examination_report",
    "SegmentFramePreviewData": "patient_examination_report",
    "SegmentFrameSelectionAction": "patient_examination_report",
    "SegmentFrameSelectorItemData": "patient_examination_report",
    "SegmentFrameSelectorPatchData": "patient_examination_report",
    "SegmentFrameSelectorPatchPayload": "patient_examination_report",
    "SegmentFrameSelectorQueryData": "patient_examination_report",
    "SegmentFrameSelectorQueryPayload": "patient_examination_report",
    "SegmentFrameSelectorResponseData": "patient_examination_report",
    "SegmentSelectionMetaData": "patient_examination_report",
    "dump_make_report_payload": "patient_examination_report",
    "dump_persisted_artifacts_payload": "patient_examination_report",
    "dump_report_submission_payload": "patient_examination_report",
    "dump_segment_frame_selection_payload": "patient_examination_report",
    "dump_selector_patch_payload": "patient_examination_report",
    "dump_selector_query_payload": "patient_examination_report",
    "report_json_safe": "patient_examination_report",
    "report_json_safe_dict": "patient_examination_report",
    "validate_segment_selection_map": "patient_examination_report",
    "PatientFindingClassificationCreateData": "patient_finding_classification",
    "PatientFindingClassificationCreatePayload": "patient_finding_classification",
    "dump_patient_finding_classification_create_payload": "patient_finding_classification",
    "validate_patient_finding_classification_create_payload": "patient_finding_classification",
    "PatientFindingClassificationNumericalDescriptorPayload": "patient_finding_classification_runtime",
    "PatientFindingClassificationNumericalDescriptorsData": "patient_finding_classification_runtime",
    "PatientFindingClassificationNumericalDescriptorsPayload": "patient_finding_classification_runtime",
    "PatientFindingClassificationSubcategoriesData": "patient_finding_classification_runtime",
    "PatientFindingClassificationSubcategoriesPayload": "patient_finding_classification_runtime",
    "PatientFindingClassificationSubcategoryPayload": "patient_finding_classification_runtime",
    "PdfFileContextPayload": "pdf_file",
    "PdfFileIdentityPayload": "pdf_file",
    "PdfFileMetaJsonObject": "pdf_file",
    "PdfFileMetaJsonValue": "pdf_file",
    "PdfFilePayload": "pdf_file",
    "PdfFileProcessingStatePayload": "pdf_file",
    "PdfFileStoragePayload": "pdf_file",
    "PdfMetaPayload": "pdf_meta",
    "PdfTypeSummaryPayload": "pdf_meta",
    "PdfRedactionBox": "pdf_redaction",
    "PdfRedactionManifest": "pdf_redaction",
    "PdfRedactionPage": "pdf_redaction",
    "PdfRedactionRequest": "pdf_redaction",
    "PdfRedactionResponse": "pdf_redaction",
    "KAnonymityResult": "pseudonymization",
    "KPseudonymizationResult": "pseudonymization",
    "QuasiIdentifierField": "pseudonymization",
    "QuasiIdentifierSubset": "pseudonymization",
    "Report": "report",
    "ReportMetaJsonObject": "report",
    "ReportMetaJsonValue": "report",
    "ReportPayload": "report",
    "ReportVersion": "report",
    "SerializedReport": "report",
    "REPORT_ANONYMIZATION_CONTRACT_VERSION": "report_anonymization",
    "ReportAnonymizationContractVersion": "report_anonymization",
    "ReportAnonymizationErrorCode": "report_anonymization",
    "ReportAnonymizationFailure": "report_anonymization",
    "ReportAnonymizationOptions": "report_anonymization",
    "ReportAnonymizationPhase": "report_anonymization",
    "ReportAnonymizationProvenance": "report_anonymization",
    "ReportAnonymizationRequest": "report_anonymization",
    "ReportAnonymizationResult": "report_anonymization",
    "ReportAnonymizationWarning": "report_anonymization",
    "ReportAnonymizationWarningCode": "report_anonymization",
    "ReportArtifactValidation": "report_anonymization",
    "ReportContext": "report_context",
    "REPORT_DRAFT_SCHEMA_VERSION": "report_draft",
    "PatientExaminationReportDraft": "report_draft",
    "ReportDraftTemplateIdentity": "report_draft",
    "dump_patient_examination_report_draft": "report_draft",
    "StudyCohortCaseRow": "study_cohort",
    "StudyCohortExaminationRow": "study_cohort",
    "StudyCohortMediaRow": "study_cohort",
    "StudyCohortReportRow": "study_cohort",
    "ExaminationCatalogDTO": "terminology_catalog",
    "IndicationCatalogDTO": "terminology_catalog",
    "LocalizedCatalogItem": "terminology_catalog",
    "TransferValidationFailureLogPayload": "transfer_validation",
    "TransferValidationLogScalar": "transfer_validation",
    "TransferValidationLogValue": "transfer_validation",
    "dump_transfer_validation_failure_log_payload": "transfer_validation",
    "UploadApiRequestData": "upload",
    "UploadApiRequestPayload": "upload",
    "upload_api_request_data_from_mapping": "upload",
    "validate_upload_api_request_payload": "upload",
    "VideoAiHuggingFaceModelPayload": "video_ai_labels",
    "VideoAiJsonObject": "video_ai_labels",
    "VideoAiLabelMutationResponsePayload": "video_ai_labels",
    "VideoAiLabelNamePayload": "video_ai_labels",
    "VideoAiLabelPayload": "video_ai_labels",
    "VideoAiLabelRenamePayload": "video_ai_labels",
    "VideoAiLabelSetPayload": "video_ai_labels",
    "VideoAiPredictionJobPayload": "video_ai_labels",
    "VideoAiPredictionModelListPayload": "video_ai_labels",
    "VideoAiPredictionModelMetaPayload": "video_ai_labels",
    "VideoAiRerunPredictionRequestPayload": "video_ai_labels",
    "VideoAiRerunPredictionResponsePayload": "video_ai_labels",
    "validate_video_ai_label_name_payload": "video_ai_labels",
    "validate_video_ai_label_rename_payload": "video_ai_labels",
    "validate_video_ai_rerun_prediction_request": "video_ai_labels",
    "video_ai_json_safe_dict": "video_ai_labels",
    "VideoCorrectionApplyMaskPayload": "video_correction",
    "VideoCorrectionApplyMaskResponsePayload": "video_correction",
    "VideoCorrectionErrorPayload": "video_correction",
    "VideoCorrectionFrameRemovalPayload": "video_correction",
    "VideoCorrectionMaskType": "video_correction",
    "VideoCorrectionProcessingMethod": "video_correction",
    "VideoCorrectionRemoveFramesResponsePayload": "video_correction",
    "VideoCorrectionRoiData": "video_correction",
    "VideoCorrectionRoiPayload": "video_correction",
    "VideoCorrectionSegmentUpdateData": "video_correction",
    "VideoCorrectionSegmentUpdatePayload": "video_correction",
    "dump_video_correction_roi_payload": "video_correction",
    "dump_video_correction_segment_update_payload": "video_correction",
    "parse_video_correction_frame_ranges": "video_correction",
    "validate_video_correction_apply_mask_payload": "video_correction",
    "validate_video_correction_frame_removal_payload": "video_correction",
    "VideoExaminationCreateData": "video_examination",
    "VideoExaminationCreatePayload": "video_examination",
    "VideoExaminationFindingData": "video_examination",
    "VideoExaminationFindingPayload": "video_examination",
    "VideoExaminationListQueryData": "video_examination",
    "VideoExaminationListQueryPayload": "video_examination",
    "VideoExaminationPathPayload": "video_examination",
    "VideoExaminationUpdateData": "video_examination",
    "VideoExaminationUpdatePayload": "video_examination",
    "dump_video_examination_create_payload": "video_examination",
    "dump_video_examination_finding_payload": "video_examination",
    "dump_video_examination_list_query_payload": "video_examination",
    "dump_video_examination_update_payload": "video_examination",
    "validate_video_examination_list_query": "video_examination",
    "validate_video_examination_path_payload": "video_examination",
    "VideoAnnotationExportConfigUpdateData": "video_export",
    "VideoAnnotationExportErrorPayload": "video_export",
    "VideoAnnotationExportFormat": "video_export",
    "VideoAnnotationExportRequestPayload": "video_export",
    "VideoAnnotationExportResultPayload": "video_export",
    "dump_video_annotation_export_update_payload": "video_export",
    "FrameSourceMode": "video_file",
    "VideoFileIdentityPayload": "video_file",
    "VideoFileMetaJsonObject": "video_file",
    "VideoFileMetaJsonValue": "video_file",
    "VideoFilePayload": "video_file",
    "VideoFileStoragePayload": "video_file",
    "VideoFileTechnicalMetadataPayload": "video_file",
    "FrameAnnotationBulkEnvelopeData": "video_frame_annotations",
    "FrameAnnotationBulkEnvelopePayload": "video_frame_annotations",
    "FrameAnnotationBulkItemData": "video_frame_annotations",
    "FrameAnnotationBulkItemPayload": "video_frame_annotations",
    "FrameAnnotationPayloadMapping": "video_frame_annotations",
    "FrameAnnotationSkipPayload": "video_frame_annotations",
    "FrameBoxAnnotationBulkEnvelopeData": "video_frame_annotations",
    "FrameBoxAnnotationBulkEnvelopePayload": "video_frame_annotations",
    "FrameBoxAnnotationBulkItemData": "video_frame_annotations",
    "FrameBoxAnnotationBulkItemPayload": "video_frame_annotations",
    "dump_frame_annotation_bulk_item": "video_frame_annotations",
    "dump_frame_box_annotation_bulk_item": "video_frame_annotations",
    "VideoFrameBoxAnnotationListResponsePayload": "video_frame_box_annotations",
    "VideoFrameBoxAnnotationMutationResponsePayload": "video_frame_box_annotations",
    "VideoFrameBoxAnnotationRequestPayload": "video_frame_box_annotations",
    "VideoFrameBoxJsonObject": "video_frame_box_annotations",
    "validate_video_frame_box_annotation_request": "video_frame_box_annotations",
    "video_frame_box_json_safe_dict": "video_frame_box_annotations",
    "VideoFrameAnnotationExportConfigPayload": "video_frame_export",
    "VideoFrameAnnotationExportFormat": "video_frame_export",
    "YamlScalar": "video_frame_export",
    "YamlValue": "video_frame_export",
    "export_config": "video_frame_export",
    "export_result": "video_frame_export",
    "load_video_frame_annotation_export_config": "video_frame_export",
    "validate_video_frame_annotation_export_config": "video_frame_export",
    "VIDEO_REIMPORT_HISTORY_KIND": "video_reimport",
    "VIDEO_REIMPORT_OPERATION": "video_reimport",
    "JsonObject": "video_reimport",
    "JsonValue": "video_reimport",
    "VideoReimportApiResponseData": "video_reimport",
    "VideoReimportApiResponsePayload": "video_reimport",
    "VideoReimportApiStatus": "video_reimport",
    "VideoReimportDispatchResult": "video_reimport",
    "VideoReimportDispatchStatus": "video_reimport",
    "VideoReimportErrorType": "video_reimport",
    "VideoReimportHistoryConfig": "video_reimport",
    "VideoReimportJobMode": "video_reimport",
    "VideoReimportJsonValue": "video_reimport",
    "VideoReimportOperation": "video_reimport",
    "VideoReimportPredictionRefreshPayload": "video_reimport",
    "VideoReimportPredictionRefreshStatus": "video_reimport",
    "VideoReimportRequestData": "video_reimport",
    "VideoReimportRequestPayload": "video_reimport",
    "VideoReimportStatus": "video_reimport",
    "dump_video_reimport_api_response": "video_reimport",
    "dump_video_reimport_request_payload": "video_reimport",
    "validate_video_reimport_request_payload": "video_reimport",
    "video_reimport_json_safe": "video_reimport",
    "video_reimport_json_safe_dict": "video_reimport",
    "OutsideFrameBlackeningHistoryConfigData": "video_segment_validation",
    "OutsideFrameBlackeningHistoryConfigPayload": "video_segment_validation",
    "PostValidationRebuildSummaryData": "video_segment_validation",
    "PostValidationRebuildSummaryPayload": "video_segment_validation",
    "VideoSegmentValidationNull": "video_segment_validation",
    "VideoSegmentValidationText": "video_segment_validation",
    "SegmentAnnotationEnsurePayload": "video_segments",
    "SegmentAnnotationInput": "video_segments",
    "SegmentAnnotationMetadataInput": "video_segments",
    "SegmentBlackenOutsidePayload": "video_segments",
    "SegmentBulkValidationItem": "video_segments",
    "SegmentBulkValidationPayload": "video_segments",
    "SegmentCrudPayload": "video_segments",
    "SegmentListQuery": "video_segments",
    "SegmentPredictionImportItem": "video_segments",
    "SegmentPredictionImportPayload": "video_segments",
    "SegmentValidationPayload": "video_segments",
    "SegmentValidationStatusPayload": "video_segments",
    "VideoSegmentsPayload": "video_segments",
    "VideoSegmentsPayloadDict": "video_segments",
    "parse_segment_annotation_input": "video_segments",
    "validate_segment_annotation_ensure_payload": "video_segments",
    "validate_segment_blacken_outside_payload": "video_segments",
    "validate_segment_bulk_validation_payload": "video_segments",
    "validate_segment_crud_payload": "video_segments",
    "validate_segment_list_query": "video_segments",
    "validate_segment_prediction_import_payload": "video_segments",
    "validate_segment_validation_payload": "video_segments",
    "validate_segment_validation_status_payload": "video_segments",
    "validate_video_segments_payload": "video_segments",
    "TemporalInferenceDispatchResult": "video_temporal_inference",
    "TemporalInferenceHistoryConfigPayload": "video_temporal_inference",
    "TemporalInferenceHistoryResultPayload": "video_temporal_inference",
    "parse_temporal_inference_history_config_payload": "video_temporal_inference",
    "parse_temporal_inference_history_result_payload": "video_temporal_inference",
    "VideoTextMetaPayload": "video_text_metadata",
    "VideoTextMetaValue": "video_text_metadata",
}

_EXPORT_ALIASES: dict[str, str] = {"LegacyNullValue": "NullValue"}


def __getattr__(name: str) -> Any:
    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    attribute_name = _EXPORT_ALIASES.get(name, name)
    value = getattr(import_module(f"{__name__}.{module_name}"), attribute_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(_EXPORT_MODULES))


__all__ = [
    "KNOWLEDGE_BASE_GRAPH_CONTRACT_VERSION",
    "LX_ANONYMIZER_PERFORMANCE_CSV_FIELDNAMES",
    "REPORT_ANONYMIZATION_CONTRACT_VERSION",
    "REPORT_DRAFT_SCHEMA_VERSION",
    "VIDEO_REIMPORT_HISTORY_KIND",
    "VIDEO_REIMPORT_OPERATION",
    "AIDataSetActiveLearningCandidateContract",
    "AIDataSetActiveLearningConfigContract",
    "AIDataSetActiveLearningSelectionContract",
    "AIDataSetAttachVideoContract",
    "AIDataSetAttachmentResultContract",
    "AIDataSetCreateContract",
    "AIDataSetFrameBucketCount",
    "AIDataSetFrameBucketDistribution",
    "AIDataSetFrameBucketSummary",
    "AIDataSetLabelDistributionEntry",
    "AIDataSetLabelFrameBucketCount",
    "AIDataSetScoredActiveLearningCandidateContract",
    "AIDataSetStandardExportScopeContract",
    "AIDataSetTargetFrameBucket",
    "AiModelSerializerInputPayload",
    "AiModelSerializerOutputPayload",
    "AnonymizationFieldQualityPayload",
    "AnonymizationMetricsFiltersPayload",
    "AnonymizationMetricsPayload",
    "AnonymizationMetricsQueryBoundsPayload",
    "AnonymizationPhiRegionMetricsPayload",
    "AnonymizationQualityMetricsPayload",
    "AnonymizationQualityPayload",
    "AnonymizationQualityResult",
    "AnonymizationQualitySummary",
    "AnonymizationWorkflowMetricsPayload",
    "ApplicationSettingsBackupSourcePayload",
    "ApplicationSettingsBackupStatusPayload",
    "ApplicationSettingsDataSetEntryPayload",
    "ApplicationSettingsDeploymentProfilePayload",
    "ApplicationSettingsDeploymentRole",
    "ApplicationSettingsPayload",
    "ByteRange",
    "CaseResolutionNewPatient",
    "CaseResolutionRequest",
    "CaseResolutionResponse",
    "CitationCore",
    "ClassificationChoiceCore",
    "ClassificationChoiceDescriptorCore",
    "ClassificationCore",
    "ClassificationTypeCore",
    "ClinicalFhirResource",
    "CodemodRenameMapPayload",
    "ContraindicationCore",
    "CoreConceptBase",
    "CoreConceptCollection",
    "CoreConceptModel",
    "CoreConceptName",
    "DescriptorValue",
    "DjangoBeatScheduleEntryPayload",
    "DjangoBeatScheduleOptionsPayload",
    "DjangoCacheConfigPayload",
    "DjangoCacheSettingsPayload",
    "DjangoRestFrameworkSettingsPayload",
    "DjangoTemplateConfigPayload",
    "DjangoTemplateOptionsPayload",
    "DocumentType",
    "DtypesRecordClassificationChoiceDescriptorPayload",
    "DtypesRecordClassificationChoicePayload",
    "DtypesRecordClassificationGroupPayload",
    "DtypesRecordFindingPayload",
    "DtypesRecordIndicationClassificationDescriptorPayload",
    "DtypesRecordIndicationClassificationPayload",
    "DtypesRecordIndicationPayload",
    "DtypesRecordInterventionGroupPayload",
    "DtypesRecordInterventionPayload",
    "DtypesRecordPersistencePayload",
    "EndoscopeImageRoiCore",
    "EndoscopyProcessorCore",
    "EventClassificationChoiceCore",
    "EventClassificationCore",
    "EventCore",
    "ExaminationCatalogDTO",
    "ExaminationCore",
    "ExaminationIndicationClassificationChoiceCore",
    "ExaminationIndicationClassificationCore",
    "ExaminationIndicationCore",
    "ExaminationReportingContext",
    "ExaminationTimeCore",
    "ExaminationTimeTypeCore",
    "ExaminationTypeCore",
    "FfmpegActiveStreamThrottleState",
    "FfmpegStreamInfo",
    "FfmpegStreamProbeEntry",
    "FfmpegStreamThrottleState",
    "FfmpegStreamThrottleStatePayload",
    "FhirClinicalBundle",
    "FhirClinicalBundleEntry",
    "FhirCodeableConcept",
    "FhirCoding",
    "FhirCondition",
    "FhirDiagnosticReport",
    "FhirObservation",
    "FhirObservationComponent",
    "FhirPatient",
    "FhirQuantity",
    "FhirReference",
    "FindingClassificationChoiceCore",
    "FindingClassificationCore",
    "FindingClassificationTypeCore",
    "FindingCore",
    "FindingInterventionCore",
    "FindingInterventionTypeCore",
    "FindingTypeCore",
    "FrameAnnotationBulkEnvelopeData",
    "FrameAnnotationBulkEnvelopePayload",
    "FrameAnnotationBulkItemData",
    "FrameAnnotationBulkItemPayload",
    "FrameAnnotationPayloadMapping",
    "FrameAnnotationRandomTaskResponsePayload",
    "FrameAnnotationSkipPayload",
    "FrameAnnotationSkipResponsePayload",
    "FrameBoxAnnotationBulkEnvelopeData",
    "FrameBoxAnnotationBulkEnvelopePayload",
    "FrameBoxAnnotationBulkItemData",
    "FrameBoxAnnotationBulkItemPayload",
    "FrameSegmentReconciliationTrack",
    "FrameSourceMode",
    "HubMediaEnvelopeMetadata",
    "HubMediaEnvelopeReceipt",
    "HubTransferReportTransferPayload",
    "HubTransferSegmentProvenancePayload",
    "HubTransferVideoSegmentPayload",
    "HubTransferVideoTransferPayload",
    "HuggingFaceModelMetaCommandData",
    "HuggingFaceModelMetaCommandPayload",
    "HuggingFaceModelMetaCommandValue",
    "IndicationCatalogDTO",
    "IndicationCore",
    "IndicationTypeCore",
    "InformationSourceCore",
    "InformationSourceTypeCore",
    "InterventionCore",
    "InterventionTypeCore",
    "JsonObject",
    "JsonValue",
    "KAnonymityResult",
    "KPseudonymizationResult",
    "KeycloakClaimsPayload",
    "KeycloakRoleContainerPayload",
    "KnowledgeBaseContract",
    "KnowledgeBaseGraphEdge",
    "KnowledgeBaseGraphNodeRef",
    "KnowledgeBaseGraphResolver",
    "KnowledgeBaseGraphSnapshot",
    "KnowledgeBaseIdentity",
    "LabValueNormalRangeData",
    "LabValueNormalRangePayload",
    "LegacyDataImportCommandOptionsPayload",
    "LegacyExaminationIdValue",
    "LegacyImageImportRowPayload",
    "LegacyImportManifestData",
    "LegacyImportManifestPayload",
    "LegacyIntOrNull",
    "LegacyNullValue",
    "LegacyTextOrNull",
    "LocalizedCatalogItem",
    "LxAnonymizerDurationStatsPayload",
    "LxAnonymizerPerformanceCsvCell",
    "LxAnonymizerPerformanceCsvRow",
    "LxAnonymizerPerformanceMediaType",
    "LxAnonymizerPerformancePayload",
    "LxAnonymizerPerformanceRunPayload",
    "LxAnonymizerPerformanceSummaryPayload",
    "MediaOperationLeaseSummary",
    "MediaOperationLeaseSummaryPayload",
    "MediaStreamDisposition",
    "MediaStreamFileKind",
    "MigrateDataDirCommandOptionsPayload",
    "MigrateDataDirManifestData",
    "MigrateDataDirManifestEntryData",
    "MigrateDataDirManifestEntryPayload",
    "MigrateDataDirManifestPayload",
    "MigrateDataDirManifestValue",
    "MigrateDataDirNull",
    "ModelInputCommandOptionsPayload",
    "ModelTrainingResultPayload",
    "NginxAccelResponseHeadersPayload",
    "OutsideFrameBlackeningHistoryConfigData",
    "OutsideFrameBlackeningHistoryConfigPayload",
    "PatientExaminationPatientDataPayload",
    "PatientExaminationReportDraft",
    "PatientExaminationReportMakeReportData",
    "PatientExaminationReportMakeReportPayload",
    "PatientExaminationReportSubmissionData",
    "PatientExaminationReportSubmissionPayload",
    "PatientFindingClassificationCreateData",
    "PatientFindingClassificationCreatePayload",
    "PatientFindingClassificationNumericalDescriptorPayload",
    "PatientFindingClassificationNumericalDescriptorsData",
    "PatientFindingClassificationNumericalDescriptorsPayload",
    "PatientFindingClassificationSubcategoriesData",
    "PatientFindingClassificationSubcategoriesPayload",
    "PatientFindingClassificationSubcategoryPayload",
    "PatientReportIdentityData",
    "PatientReportIdentityPayload",
    "PdfFileContextPayload",
    "PdfFileIdentityPayload",
    "PdfFileMetaJsonObject",
    "PdfFileMetaJsonValue",
    "PdfFilePayload",
    "PdfFileProcessingStatePayload",
    "PdfFileStoragePayload",
    "PdfMetaPayload",
    "PdfRedactionBox",
    "PdfRedactionManifest",
    "PdfRedactionPage",
    "PdfRedactionRequest",
    "PdfRedactionResponse",
    "PdfTypeSummaryPayload",
    "PostValidationRebuildSummaryData",
    "PostValidationRebuildSummaryPayload",
    "QualityEvaluationStatus",
    "QuasiIdentifierField",
    "QuasiIdentifierSubset",
    "ReadyForExportResult",
    "ReapQuarantineCommandOptionsPayload",
    "ReapUploadJobSourcesCommandOptionsPayload",
    "ReconcileFrameSegmentAnnotationsCommandOptionsPayload",
    "ReconcileMediaIntegrityCommandOptionsPayload",
    "ReconcileSegmentValidationStateCommandOptionsPayload",
    "ReconcileVideoFormatsCommandOptionsPayload",
    "RefreshAuditLedgerIntegrityCommandOptionsPayload",
    "RegisterAiModelCommandOptionsPayload",
    "RegisterAiModelMetaPayload",
    "Report",
    "ReportAnonymizationContractVersion",
    "ReportAnonymizationErrorCode",
    "ReportAnonymizationFailure",
    "ReportAnonymizationOptions",
    "ReportAnonymizationPhase",
    "ReportAnonymizationProvenance",
    "ReportAnonymizationRequest",
    "ReportAnonymizationResult",
    "ReportAnonymizationWarning",
    "ReportAnonymizationWarningCode",
    "ReportArtifactValidation",
    "ReportContext",
    "ReportDraftTemplateIdentity",
    "ReportExportFrameDetailData",
    "ReportJsonObject",
    "ReportJsonValue",
    "ReportMetaJsonObject",
    "ReportMetaJsonValue",
    "ReportPayload",
    "ReportPersistedArtifactsData",
    "ReportPersistedArtifactsPayload",
    "ReportSegmentFrameSelectionData",
    "ReportSegmentFrameSelectionPayload",
    "ReportSegmentSelectionMap",
    "ReportStatus",
    "ReportTemplateGraphProjection",
    "ReportVersion",
    "ResolvedDiagnosticReport",
    "RoiBoxCore",
    "RuntimeStorageContractPayload",
    "SegmentAnnotationEnsurePayload",
    "SegmentAnnotationInput",
    "SegmentAnnotationMetadataInput",
    "SegmentAttachedFindingData",
    "SegmentBlackenOutsidePayload",
    "SegmentBulkValidationItem",
    "SegmentBulkValidationPayload",
    "SegmentCrudPayload",
    "SegmentFrameControlsData",
    "SegmentFramePreviewData",
    "SegmentFrameSelectionAction",
    "SegmentFrameSelectorItemData",
    "SegmentFrameSelectorPatchData",
    "SegmentFrameSelectorPatchPayload",
    "SegmentFrameSelectorQueryData",
    "SegmentFrameSelectorQueryPayload",
    "SegmentFrameSelectorResponseData",
    "SegmentListQuery",
    "SegmentPredictionImportItem",
    "SegmentPredictionImportPayload",
    "SegmentSelectionMetaData",
    "SegmentValidationPayload",
    "SegmentValidationStatusPayload",
    "SensitiveMetaHandlingPolicy",
    "SensitiveMetaPatientRepairCreatePayload",
    "SensitiveMetaPatientRepairData",
    "SensitiveMetaPatientRepairUpdatePayload",
    "SensitiveMetaRepairValue",
    "SerializedReport",
    "SetupEndoregDbCommandOptionsPayload",
    "ShowUrlsCommandOptionsPayload",
    "ShowUrlsRoutePayload",
    "ShowUrlsRoutesPayload",
    "StorageManagementCommandOptionsPayload",
    "StorageManagementInfoPayload",
    "StreamThrottleMode",
    "StudyCohortCaseRow",
    "StudyCohortExaminationRow",
    "StudyCohortMediaRow",
    "StudyCohortReportRow",
    "TemporalInferenceDispatchResult",
    "TemporalInferenceHistoryConfigPayload",
    "TemporalInferenceHistoryResultPayload",
    "TrainImageMultilabelModelCommandOptionsPayload",
    "TrainPhiRegionDetectorCommandOptionsPayload",
    "TranscodeVideoCommandOptionsPayload",
    "TranscodeVideoQualityMode",
    "TransferValidationFailureLogPayload",
    "TransferValidationLogScalar",
    "TransferValidationLogValue",
    "UnitCore",
    "UnitTypeCore",
    "UploadApiRequestData",
    "UploadApiRequestPayload",
    "ValidateRuntimeStorageContractCommandOptionsPayload",
    "ValidateVideoFileStatus",
    "ValidateVideoFileStatusPayload",
    "ValidateVideoFilesCommandOptionsPayload",
    "ValidationError",
    "VerboseManagementCommandOptionsPayload",
    "VideoAiHuggingFaceModelPayload",
    "VideoAiJsonObject",
    "VideoAiLabelMutationResponsePayload",
    "VideoAiLabelNamePayload",
    "VideoAiLabelPayload",
    "VideoAiLabelRenamePayload",
    "VideoAiLabelSetPayload",
    "VideoAiPredictionJobPayload",
    "VideoAiPredictionModelListPayload",
    "VideoAiPredictionModelMetaPayload",
    "VideoAiRerunPredictionRequestPayload",
    "VideoAiRerunPredictionResponsePayload",
    "VideoAnnotationExportConfigUpdateData",
    "VideoAnnotationExportErrorPayload",
    "VideoAnnotationExportFormat",
    "VideoAnnotationExportRequestPayload",
    "VideoAnnotationExportResultPayload",
    "VideoCorrectionApplyMaskPayload",
    "VideoCorrectionApplyMaskResponsePayload",
    "VideoCorrectionErrorPayload",
    "VideoCorrectionFrameRemovalPayload",
    "VideoCorrectionMaskType",
    "VideoCorrectionProcessingMethod",
    "VideoCorrectionRemoveFramesResponsePayload",
    "VideoCorrectionRoiData",
    "VideoCorrectionRoiPayload",
    "VideoCorrectionSegmentUpdateData",
    "VideoCorrectionSegmentUpdatePayload",
    "VideoExaminationCreateData",
    "VideoExaminationCreatePayload",
    "VideoExaminationFindingData",
    "VideoExaminationFindingPayload",
    "VideoExaminationListQueryData",
    "VideoExaminationListQueryPayload",
    "VideoExaminationPathPayload",
    "VideoExaminationUpdateData",
    "VideoExaminationUpdatePayload",
    "VideoFileIdentityPayload",
    "VideoFileMetaJsonObject",
    "VideoFileMetaJsonValue",
    "VideoFilePayload",
    "VideoFileStoragePayload",
    "VideoFileTechnicalMetadataPayload",
    "VideoFrameAnnotationExportConfigPayload",
    "VideoFrameAnnotationExportFormat",
    "VideoFrameBoxAnnotationListResponsePayload",
    "VideoFrameBoxAnnotationMutationResponsePayload",
    "VideoFrameBoxAnnotationRequestPayload",
    "VideoFrameBoxJsonObject",
    "VideoPathRepairFileIndex",
    "VideoPathRepairFileInfoPayload",
    "VideoReadyForExportData",
    "VideoReadyForExportPayload",
    "VideoReimportApiResponseData",
    "VideoReimportApiResponsePayload",
    "VideoReimportApiStatus",
    "VideoReimportDispatchResult",
    "VideoReimportDispatchStatus",
    "VideoReimportErrorType",
    "VideoReimportHistoryConfig",
    "VideoReimportJobMode",
    "VideoReimportJsonValue",
    "VideoReimportOperation",
    "VideoReimportPredictionRefreshPayload",
    "VideoReimportPredictionRefreshStatus",
    "VideoReimportRequestData",
    "VideoReimportRequestPayload",
    "VideoReimportStatus",
    "VideoSegmentValidationNull",
    "VideoSegmentValidationText",
    "VideoSegmentsPayload",
    "VideoSegmentsPayloadDict",
    "VideoTextMetaPayload",
    "VideoTextMetaValue",
    "YamlScalar",
    "YamlValue",
    "build_examination_reporting_context",
    "build_knowledge_base_graph_snapshot",
    "canonical_payload_to_storage",
    "core_concept_to_storage",
    "dump_dtypes_record_persistence_payload",
    "dump_ffmpeg_stream_throttle_state",
    "dump_frame_annotation_bulk_item",
    "dump_frame_box_annotation_bulk_item",
    "dump_legacy_import_manifest",
    "dump_lx_anonymizer_performance_run_csv_row",
    "dump_make_report_payload",
    "dump_media_operation_lease_summary",
    "dump_patient_examination_report_draft",
    "dump_patient_finding_classification_create_payload",
    "dump_persisted_artifacts_payload",
    "dump_report_submission_payload",
    "dump_segment_frame_selection_payload",
    "dump_selector_patch_payload",
    "dump_selector_query_payload",
    "dump_sensitive_meta_patient_repair_create_payload",
    "dump_sensitive_meta_patient_repair_update_payload",
    "dump_transfer_validation_failure_log_payload",
    "dump_video_annotation_export_update_payload",
    "dump_video_correction_roi_payload",
    "dump_video_correction_segment_update_payload",
    "dump_video_examination_create_payload",
    "dump_video_examination_finding_payload",
    "dump_video_examination_list_query_payload",
    "dump_video_examination_update_payload",
    "dump_video_ready_for_export_payload",
    "dump_video_reimport_api_response",
    "dump_video_reimport_request_payload",
    "export_config",
    "export_result",
    "huggingface_model_meta_command_data_from_mapping",
    "kb_to_core_concepts_payload",
    "load_video_frame_annotation_export_config",
    "parse_dtypes_record_persistence_payload",
    "parse_segment_annotation_input",
    "parse_temporal_inference_history_config_payload",
    "parse_temporal_inference_history_result_payload",
    "parse_video_correction_frame_ranges",
    "record_to_core_concept",
    "records_to_core_concepts",
    "report_json_safe",
    "report_json_safe_dict",
    "upload_api_request_data_from_mapping",
    "validate_ai_model_serializer_input_payload",
    "validate_ai_model_serializer_output_payload",
    "validate_codemod_rename_map",
    "validate_ffmpeg_stream_info",
    "validate_hub_media_receipt_matches_envelope",
    "validate_hub_transfer_report_payload",
    "validate_hub_transfer_video_payload",
    "validate_huggingface_model_meta_command_payload",
    "validate_keycloak_claims",
    "validate_model_training_result",
    "validate_optional_knowledge_base_identity",
    "validate_patient_finding_classification_create_payload",
    "validate_segment_annotation_ensure_payload",
    "validate_segment_blacken_outside_payload",
    "validate_segment_bulk_validation_payload",
    "validate_segment_crud_payload",
    "validate_segment_list_query",
    "validate_segment_prediction_import_payload",
    "validate_segment_selection_map",
    "validate_segment_validation_payload",
    "validate_segment_validation_status_payload",
    "validate_upload_api_request_payload",
    "validate_video_ai_label_name_payload",
    "validate_video_ai_label_rename_payload",
    "validate_video_ai_rerun_prediction_request",
    "validate_video_correction_apply_mask_payload",
    "validate_video_correction_frame_removal_payload",
    "validate_video_examination_list_query",
    "validate_video_examination_path_payload",
    "validate_video_frame_annotation_export_config",
    "validate_video_frame_box_annotation_request",
    "validate_video_ready_for_export_payload",
    "validate_video_reimport_request_payload",
    "validate_video_segments_payload",
    "video_ai_json_safe_dict",
    "video_frame_box_json_safe_dict",
    "video_reimport_json_safe",
    "video_reimport_json_safe_dict",
]
