from typing import Dict, Union

from .knowledge_base_deep import (
    KB_DEEP_DDICT_BY_NAME,
    KB_DEEP_DDICT_LIST,
    KB_DEEP_UNION_DDICT_LIST,
    KB_DEEP_UNION_DDICT_TYPE_LIST,
)
from .knowledge_base_shallow import (
    KB_SHALLOW_DDICT_BY_NAME,
    KB_SHALLOW_DDICT_LIST,
    KB_SHALLOW_UNION_DDICT_LIST,
    KB_SHALLOW_UNION_DDICT_TYPE_LIST,
)
from .ledger import (
    LEDGER_DDICT_BY_NAME,
    LEDGER_DDICT_LIST,
    LEDGER_UNION_DDICT_LIST,
    LEDGER_UNION_DDICT_TYPE_LIST,
)

KB_DDICT_LIST = KB_SHALLOW_DDICT_LIST + KB_DEEP_DDICT_LIST

KB_UNION_DDICT_LIST = Union[
    KB_SHALLOW_UNION_DDICT_LIST,
    KB_DEEP_UNION_DDICT_LIST,
]

KB_UNION_DDICT_TYPE_LIST = Union[
    KB_SHALLOW_UNION_DDICT_TYPE_LIST,
    KB_DEEP_UNION_DDICT_TYPE_LIST,
]

UNION_DDICT_TYPE_LIST = Union[KB_UNION_DDICT_TYPE_LIST, LEDGER_UNION_DDICT_TYPE_LIST]


KB_DDICTS_BY_NAME: Dict[str, KB_UNION_DDICT_TYPE_LIST] = {}
KB_DDICTS_BY_NAME.update(KB_SHALLOW_DDICT_BY_NAME)
KB_DDICTS_BY_NAME.update(KB_DEEP_DDICT_BY_NAME)


DDICTS_BY_NAME: Dict[str, UNION_DDICT_TYPE_LIST] = {}
DDICTS_BY_NAME.update(KB_DDICTS_BY_NAME)
DDICTS_BY_NAME.update(LEDGER_DDICT_BY_NAME)


__all__ = [
    "KB_DDICT_LIST",
    "KB_UNION_DDICT_LIST",
    "KB_UNION_DDICT_TYPE_LIST",
    "KB_DDICTS_BY_NAME",
    "LEDGER_DDICT_LIST",
    "LEDGER_UNION_DDICT_LIST",
    "LEDGER_UNION_DDICT_TYPE_LIST",
    "LEDGER_DDICT_BY_NAME",
    "UNION_DDICT_TYPE_LIST",
    "DDICTS_BY_NAME",
]
