from .knowledge_base import (
    KB_DDICTS,
    KB_MODEL_NAMES_LITERAL,
    KB_MODEL_NAMES_ORDERED,
    KB_MODELS,
    KB_MODELS_DJANGO,
)
from .ledger import (
    L_DDICTS,
    L_MODEL_NAMES_LITERAL,
    L_MODEL_NAMES_ORDERED,
    L_MODELS,
    L_MODELS_DJANGO,
)

type MODEL_NAMES_LITERAL = KB_MODEL_NAMES_LITERAL | L_MODEL_NAMES_LITERAL

MODEL_NAMES = KB_MODEL_NAMES_ORDERED + L_MODEL_NAMES_ORDERED

type MODELS = KB_MODELS | L_MODELS
type MODELS_DJANGO = KB_MODELS_DJANGO | L_MODELS_DJANGO
type DDICTS = KB_DDICTS | L_DDICTS
