from typing import TypeAlias

from .knowledge_base import (
    KB_DDICTS,
    KB_MODEL_NAMES_LITERAL,
    KB_MODEL_NAMES_ORDERED,
    KB_MODELS,
    KB_MODELS_DJANGO,
)
from .ledger import (
    L_DDICTS,
    L_MODEL_NAMES_LITERAL,
    L_MODEL_NAMES_ORDERED,
    L_MODELS,
    L_MODELS_DJANGO,
)

MODEL_NAMES_LITERAL: TypeAlias = KB_MODEL_NAMES_LITERAL | L_MODEL_NAMES_LITERAL

MODEL_NAMES = KB_MODEL_NAMES_ORDERED + L_MODEL_NAMES_ORDERED

MODELS: TypeAlias = KB_MODELS | L_MODELS
MODELS_DJANGO: TypeAlias = KB_MODELS_DJANGO | L_MODELS_DJANGO
DDICTS: TypeAlias = KB_DDICTS | L_DDICTS
