from typing import Union

from .knowledge_base_deep import (
    KB_DEEP_PYDANTIC_BY_NAME,
    KB_DEEP_PYDANTIC_BY_NAME_TYPE,
    KB_DEEP_PYDANTIC_LIST,
    KB_DEEP_UNION_PYDANTIC_LIST,
    KB_DEEP_UNION_PYDANTIC_TYPE_LIST,
)
from .knowledge_base_shallow import (
    KB_SHALLOW_PYDANTIC_BY_NAME,
    KB_SHALLOW_PYDANTIC_BY_NAME_TYPE,
    KB_SHALLOW_PYDANTIC_LIST,
    KB_SHALLOW_UNION_PYDANTIC_LIST,
    KB_SHALLOW_UNION_PYDANTIC_TYPE_LIST,
)
from .ledger import (
    LEDGER_PYDANTIC_BY_NAME,
    LEDGER_PYDANTIC_BY_NAME_TYPE,
    LEDGER_PYDANTIC_LIST,
    LEDGER_UNION_PYDANTIC_LIST,
    LEDGER_UNION_PYDANTIC_TYPE_LIST,
)

KB_PYDANTIC_LIST = KB_SHALLOW_PYDANTIC_LIST + KB_DEEP_PYDANTIC_LIST

KB_UNION_PYDANTIC_LIST = Union[
    KB_SHALLOW_UNION_PYDANTIC_LIST,
    KB_DEEP_UNION_PYDANTIC_LIST,
]

KB_UNION_PYDANTIC_TYPE_LIST = Union[
    KB_SHALLOW_UNION_PYDANTIC_TYPE_LIST,
    KB_DEEP_UNION_PYDANTIC_TYPE_LIST,
]

UNION_PYDANTIC_TYPE_LIST = Union[
    KB_UNION_PYDANTIC_TYPE_LIST, LEDGER_UNION_PYDANTIC_TYPE_LIST
]


__all__ = [
    "KB_PYDANTIC_LIST",
    "KB_UNION_PYDANTIC_LIST",
    "KB_UNION_PYDANTIC_TYPE_LIST",
    "LEDGER_PYDANTIC_LIST",
    "LEDGER_UNION_PYDANTIC_LIST",
    "LEDGER_UNION_PYDANTIC_TYPE_LIST",
    "LEDGER_PYDANTIC_BY_NAME",
    "UNION_PYDANTIC_TYPE_LIST",
    "KB_DEEP_PYDANTIC_BY_NAME_TYPE",
    "KB_SHALLOW_PYDANTIC_BY_NAME_TYPE",
    "LEDGER_PYDANTIC_BY_NAME_TYPE",
    "KB_DEEP_PYDANTIC_BY_NAME",
    "KB_SHALLOW_PYDANTIC_BY_NAME",
]
