# Generated by Django 6.0 on 2025-12-25 18:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lx_django", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientExamination",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("external_ids", models.JSONField(default=dict)),
                ("date", models.DateTimeField(blank=True, null=True)),
                (
                    "examination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_examinations",
                        to="lx_django.examination",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examinations",
                        to="lx_django.patient",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PatientFinding",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("external_ids", models.JSONField(default=dict)),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_findings",
                        to="lx_django.finding",
                    ),
                ),
                (
                    "patient_examination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="lx_django.patientexamination",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PatientFindingClassificationChoice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("external_ids", models.JSONField(default=dict)),
                (
                    "choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_finding_classification_choices",
                        to="lx_django.classificationchoice",
                    ),
                ),
                (
                    "classification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_finding_classification_choices",
                        to="lx_django.classification",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PatientFindingClassificationChoiceDescriptor",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("external_ids", models.JSONField(default=dict)),
                ("descriptor_value", models.CharField(max_length=255)),
                (
                    "choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descriptors",
                        to="lx_django.patientfindingclassificationchoice",
                    ),
                ),
                (
                    "descriptor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_finding_classification_choice_descriptors",
                        to="lx_django.classificationchoicedescriptor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PatientFindingClassifications",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("external_ids", models.JSONField(default=dict)),
                (
                    "finding",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classifications",
                        to="lx_django.patientfinding",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="patientfindingclassificationchoice",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="lx_django.patientfindingclassifications",
            ),
        ),
        migrations.CreateModel(
            name="PatientFindingInterventions",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("external_ids", models.JSONField(default=dict)),
                (
                    "finding",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interventions",
                        to="lx_django.patientfinding",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PatientFindingIntervention",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("external_ids", models.JSONField(default=dict)),
                (
                    "intervention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_finding_interventions",
                        to="lx_django.intervention",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interventions",
                        to="lx_django.patientfindinginterventions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PatientIndication",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("external_ids", models.JSONField(default=dict)),
                (
                    "indication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_indications",
                        to="lx_django.indication",
                    ),
                ),
                (
                    "patient_examination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indications",
                        to="lx_django.patientexamination",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
