# Generated by Django 6.0 on 2026-01-09 10:52

import typing
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CitationDjango",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("kb_module_name", models.CharField(default="unknown", max_length=255)),
                ("citation_key", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=1024)),
                ("abstract", models.CharField(blank=True, max_length=5000, null=True)),
                ("authors", models.CharField(blank=True, max_length=2000)),
                ("publication_year", models.IntegerField(blank=True, null=True)),
                (
                    "publication_month",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("journal", models.CharField(blank=True, max_length=255, null=True)),
                ("publisher", models.CharField(blank=True, max_length=255, null=True)),
                ("volume", models.CharField(blank=True, max_length=50, null=True)),
                ("issue", models.CharField(blank=True, max_length=50, null=True)),
                ("pages", models.CharField(blank=True, max_length=50, null=True)),
                ("doi", models.CharField(blank=True, max_length=255, null=True)),
                ("url", models.CharField(blank=True, max_length=1024, null=True)),
                ("entry_type", models.CharField(blank=True, max_length=100, null=True)),
                ("language", models.CharField(blank=True, max_length=50, null=True)),
                ("keywords", models.CharField(blank=True, max_length=2000)),
                ("identifiers", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, typing.Generic),
        ),
    ]
