# Generated by Django 6.0 on 2026-01-12 08:39

import django.db.models.deletion
import typing
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CitationDjango",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("kb_module_name", models.CharField(default="unknown", max_length=255)),
                ("citation_key", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=1024)),
                ("abstract", models.CharField(blank=True, max_length=5000, null=True)),
                ("authors", models.CharField(blank=True, max_length=2000)),
                ("publication_year", models.IntegerField(blank=True, null=True)),
                (
                    "publication_month",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("journal", models.CharField(blank=True, max_length=255, null=True)),
                ("publisher", models.CharField(blank=True, max_length=255, null=True)),
                ("volume", models.CharField(blank=True, max_length=50, null=True)),
                ("issue", models.CharField(blank=True, max_length=50, null=True)),
                ("pages", models.CharField(blank=True, max_length=50, null=True)),
                ("doi", models.CharField(blank=True, max_length=255, null=True)),
                ("url", models.CharField(blank=True, max_length=1024, null=True)),
                ("entry_type", models.CharField(blank=True, max_length=100, null=True)),
                ("language", models.CharField(blank=True, max_length=50, null=True)),
                ("keywords", models.CharField(blank=True, max_length=2000)),
                ("identifiers", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, typing.Generic),
        ),
        migrations.CreateModel(
            name="IndicationTypeDjango",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("kb_module_name", models.CharField(default="unknown", max_length=255)),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, typing.Generic),
        ),
        migrations.CreateModel(
            name="InterventionDjango",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("kb_module_name", models.CharField(default="unknown", max_length=255)),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, typing.Generic),
        ),
        migrations.CreateModel(
            name="InterventionTypeDjango",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("kb_module_name", models.CharField(default="unknown", max_length=255)),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, typing.Generic),
        ),
        migrations.CreateModel(
            name="UnitDjango",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("kb_module_name", models.CharField(default="unknown", max_length=255)),
                ("abbreviation", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, typing.Generic),
        ),
        migrations.CreateModel(
            name="UnitTypeDjango",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("kb_module_name", models.CharField(default="unknown", max_length=255)),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, typing.Generic),
        ),
        migrations.CreateModel(
            name="IndicationDjango",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("kb_module_name", models.CharField(default="unknown", max_length=255)),
                (
                    "indication_types",
                    models.ManyToManyField(
                        related_name="indications",
                        to="lx_dtypes_django.indicationtypedjango",
                    ),
                ),
                (
                    "interventions",
                    models.ManyToManyField(
                        related_name="indications",
                        to="lx_dtypes_django.interventiondjango",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, typing.Generic),
        ),
        migrations.AddField(
            model_name="interventiondjango",
            name="intervention_types",
            field=models.ManyToManyField(
                related_name="interventions",
                to="lx_dtypes_django.interventiontypedjango",
            ),
        ),
        migrations.CreateModel(
            name="ClassificationChoiceDescriptorDjango",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("kb_module_name", models.CharField(default="unknown", max_length=255)),
                (
                    "classification_choice_descriptor_type",
                    models.CharField(
                        choices=[
                            ("numeric", "numeric"),
                            ("text", "text"),
                            ("boolean", "boolean"),
                            ("selection", "selection"),
                        ],
                        default="numeric",
                        max_length=32,
                    ),
                ),
                (
                    "numeric_distribution",
                    models.CharField(
                        choices=[
                            ("normal", "normal"),
                            ("log_normal", "log_normal"),
                            ("uniform", "uniform"),
                            ("exponential", "exponential"),
                            ("unknown", "unknown"),
                        ],
                        default="uniform",
                        max_length=32,
                    ),
                ),
                ("numeric_min", models.FloatField()),
                ("numeric_max", models.FloatField()),
                ("numeric_distribution_params", models.JSONField()),
                ("text_max_length", models.IntegerField()),
                ("default_value_str", models.CharField(max_length=255)),
                ("default_value_num", models.FloatField()),
                ("default_value_bool", models.BooleanField()),
                ("selection_options", models.JSONField()),
                ("selection_multiple", models.BooleanField()),
                ("selection_multiple_n_min", models.IntegerField()),
                ("selection_multiple_n_max", models.IntegerField()),
                ("selection_default_options", models.JSONField()),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classification_choice_descriptors",
                        to="lx_dtypes_django.unitdjango",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, typing.Generic),
        ),
        migrations.AddField(
            model_name="unitdjango",
            name="unit_types",
            field=models.ManyToManyField(
                related_name="units", to="lx_dtypes_django.unittypedjango"
            ),
        ),
    ]
