# Generated by Django 6.0 on 2026-01-09 13:14

import typing
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lx_dtypes_django", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterventionTypeDjango",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("kb_module_name", models.CharField(default="unknown", max_length=255)),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, typing.Generic),
        ),
        migrations.CreateModel(
            name="InterventionDjango",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("name_de", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("kb_module_name", models.CharField(default="unknown", max_length=255)),
                (
                    "intervention_types",
                    models.ManyToManyField(
                        related_name="intervention_types",
                        to="lx_dtypes_django.interventiontypedjango",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, typing.Generic),
        ),
    ]
