# Generated by Django 6.0 on 2026-03-30 14:37

import django.db.models.deletion
import typing
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lx_dtypes_django", "0002_pexaminationdjango_knowledge_base_identity"),
    ]

    operations = [
        migrations.AddField(
            model_name="findingdjango",
            name="caused_by_interventions",
            field=models.ManyToManyField(
                blank=True,
                related_name="caused_by_findings",
                to="lx_dtypes_django.interventiondjango",
            ),
        ),
        migrations.AddField(
            model_name="indicationdjango",
            name="classifications",
            field=models.ManyToManyField(
                related_name="indications", to="lx_dtypes_django.classificationdjango"
            ),
        ),
        migrations.CreateModel(
            name="PIndicationClassificationDjango",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tags", models.CharField(blank=True, max_length=1024)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("external_ids", models.JSONField(default=dict)),
                (
                    "classification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_indication_classifications",
                        to="lx_dtypes_django.classificationdjango",
                    ),
                ),
                (
                    "classification_choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_indication_classifications",
                        to="lx_dtypes_django.classificationchoicedjango",
                    ),
                ),
                (
                    "patient_indication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_indication_classifications",
                        to="lx_dtypes_django.pindicationdjango",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(typing.Generic, models.Model),
        ),
        migrations.CreateModel(
            name="PIndicationClassificationDescriptorDjango",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tags", models.CharField(blank=True, max_length=1024)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("external_ids", models.JSONField(default=dict)),
                ("descriptor_value", models.CharField(max_length=255)),
                (
                    "classification_choice_descriptor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_indication_classification_descriptors",
                        to="lx_dtypes_django.classificationchoicedescriptordjango",
                    ),
                ),
                (
                    "patient_indication_classification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_indication_classification_descriptors",
                        to="lx_dtypes_django.pindicationclassificationdjango",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(typing.Generic, models.Model),
        ),
    ]
