# Generated by Django 6.0.1 on 2026-03-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lx_dtypes_django", "0002_pexaminationdjango_knowledge_base_identity"),
    ]

    operations = [
        migrations.AddField(
            model_name="findingdjango",
            name="caused_by_interventions",
            field=models.ManyToManyField(
                blank=True,
                related_name="caused_by_findings",
                to="lx_dtypes_django.interventiondjango",
            ),
        ),
    ]
