# Generated by Django 6.0 on 2026-03-25 11:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lx_dtypes_django", "0002_pexaminationdjango_knowledge_base_identity"),
    ]

    # This branch was superseded by 0003_findingdjango_caused_by_interventions_and_more,
    # which already adds the same ManyToManyField. Keeping this migration as a no-op
    # preserves the merge graph while avoiding duplicate implicit through-table creation.
    operations = []
