# Generated by Django 6.0.3 on 2026-04-02 08:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lx_dtypes_django", "0003_findingdjango_caused_by_interventions"),
        ("lx_dtypes_django", "0003_findingdjango_caused_by_interventions_and_more"),
    ]

    operations = []
