# Generated by Django 6.0 on 2026-01-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lx_dtypes_django", "0003_classificationtypedjango_classificationdjango"),
    ]

    operations = [
        migrations.AddField(
            model_name="classificationdjango",
            name="classification_choices",
            field=models.ManyToManyField(
                related_name="classifications",
                to="lx_dtypes_django.classificationchoicedjango",
            ),
        ),
    ]
