# Generated by Django 6.0 on 2026-01-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "lx_dtypes_django",
            "0007_informationsourcetypedjango_informationsourcedjango",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="classificationchoicedescriptordjango",
            name="numeric_max",
            field=models.FloatField(default=float("inf")),
        ),
        migrations.AlterField(
            model_name="classificationchoicedescriptordjango",
            name="numeric_min",
            field=models.FloatField(default=float("-inf")),
        ),
    ]
