# Generated by Django 6.0 on 2026-01-12 14:50

import lx_dtypes.factories.typed_dicts
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "lx_dtypes_django",
            "0008_alter_classificationchoicedescriptordjango_numeric_max_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="classificationchoicedescriptordjango",
            name="numeric_distribution_params",
            field=models.JSONField(
                default=lx_dtypes.factories.typed_dicts.numeric_distribution_params_dict_factory
            ),
        ),
        migrations.AlterField(
            model_name="classificationchoicedescriptordjango",
            name="selection_options",
            field=models.JSONField(
                default=lx_dtypes.factories.typed_dicts.selection_default_options_dict_factory
            ),
        ),
        migrations.AlterField(
            model_name="classificationchoicedjango",
            name="classification_choice_descriptors",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="classification_choices",
                to="lx_dtypes_django.classificationchoicedescriptordjango",
            ),
        ),
    ]
