# Generated by Django 6.0 on 2026-01-12 14:52

import lx_dtypes.factories.literals
import typing
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "lx_dtypes_django",
            "0009_alter_classificationchoicedescriptordjango_numeric_distribution_params_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CenterDjango",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tags", models.CharField(blank=True, max_length=1024)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default=lx_dtypes.factories.literals.str_unknown_factory,
                        max_length=256,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, typing.Generic),
        ),
        migrations.AlterField(
            model_name="classificationchoicedjango",
            name="classification_choice_descriptors",
            field=models.ManyToManyField(
                blank=True,
                related_name="classification_choices",
                to="lx_dtypes_django.classificationchoicedescriptordjango",
            ),
        ),
    ]
