# Generated by Django 6.0 on 2026-01-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lx_dtypes_django", "0010_centerdjango_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="centerdjango",
            name="external_ids",
            field=models.JSONField(default=dict),
        ),
    ]
