# Generated by Django 6.0 on 2026-01-15 08:51

import django.db.models.deletion
import typing
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lx_dtypes_django", "0014_pindicationdjango"),
    ]

    operations = [
        migrations.CreateModel(
            name="PFindingClassificationsDjango",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tags", models.CharField(blank=True, max_length=1024)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("external_ids", models.JSONField(default=dict)),
                (
                    "patient_finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_finding_classifications",
                        to="lx_dtypes_django.pfindingdjango",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, typing.Generic),
        ),
    ]
