# Generated by Django 6.0 on 2026-01-15 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lx_dtypes_django", "0016_pfindingclassificationchoicedjango"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pfindingclassificationchoicedjango",
            old_name="patient_finding_classification",
            new_name="patient_finding_classifications",
        ),
    ]
