# Generated by Django 6.0 on 2026-01-15 10:30

import django.db.models.deletion
import typing
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "lx_dtypes_django",
            "0017_rename_patient_finding_classification_pfindingclassificationchoicedjango_patient_finding_classificat",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PFindingClassificationChoiceDescriptorDjango",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tags", models.CharField(blank=True, max_length=1024)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("external_ids", models.JSONField(default=dict)),
                ("descriptor_value", models.CharField(max_length=255)),
                (
                    "classification_choice_descriptor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_finding_classification_choice_descriptors",
                        to="lx_dtypes_django.classificationchoicedescriptordjango",
                    ),
                ),
                (
                    "patient_finding_classification_choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_finding_classification_choice_descriptors",
                        to="lx_dtypes_django.pfindingclassificationchoicedjango",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, typing.Generic),
        ),
    ]
