from typing import Dict, Mapping, Union, cast

from .knowledge_base_deep import (
    KB_DEEP_DDICT_BY_NAME,
    KB_DEEP_DDICT_BY_NAME_TYPE,
    KB_DEEP_DDICT_LIST,
    KB_DEEP_UNION_DDICT_LIST,
    KB_DEEP_UNION_DDICT_TYPE_LIST,
)
from .knowledge_base_shallow import (
    KB_SHALLOW_DDICT_BY_NAME,
    KB_SHALLOW_DDICT_BY_NAME_TYPE,
    KB_SHALLOW_DDICT_LIST,
    KB_SHALLOW_UNION_DDICT_LIST,
    KB_SHALLOW_UNION_DDICT_TYPE_LIST,
)
from .ledger import (
    LEDGER_DDICT_BY_NAME,
    LEDGER_DDICT_BY_NAME_REVERSED,
    LEDGER_DDICT_LIST,
    LEDGER_UNION_DDICT_LIST,
    LEDGER_UNION_DDICT_TYPE_LIST,
)

KB_DDICT_LIST = KB_SHALLOW_DDICT_LIST + KB_DEEP_DDICT_LIST

KB_UNION_DDICT_LIST = Union[
    KB_SHALLOW_UNION_DDICT_LIST,
    KB_DEEP_UNION_DDICT_LIST,
]

KB_UNION_DDICT_TYPE_LIST = Union[
    KB_SHALLOW_UNION_DDICT_TYPE_LIST,
    KB_DEEP_UNION_DDICT_TYPE_LIST,
]

UNION_DDICT_TYPE_LIST = Union[KB_UNION_DDICT_TYPE_LIST, LEDGER_UNION_DDICT_TYPE_LIST]


KB_DDICTS_BY_NAME_REVERSED: Dict[KB_UNION_DDICT_TYPE_LIST, str] = {}


DDICTS_BY_NAME_REVERSED: Dict[UNION_DDICT_TYPE_LIST, str] = {}
DDICTS_BY_NAME_REVERSED.update(
    cast(Mapping[UNION_DDICT_TYPE_LIST, str], KB_DDICTS_BY_NAME_REVERSED)
)
DDICTS_BY_NAME_REVERSED.update(
    cast(Mapping[UNION_DDICT_TYPE_LIST, str], LEDGER_DDICT_BY_NAME_REVERSED)
)

__all__ = [
    "KB_DDICT_LIST",
    "KB_UNION_DDICT_LIST",
    "KB_UNION_DDICT_TYPE_LIST",
    "KB_DEEP_DDICT_BY_NAME",
    "KB_DEEP_DDICT_BY_NAME_TYPE",
    "LEDGER_DDICT_LIST",
    "LEDGER_UNION_DDICT_LIST",
    "LEDGER_UNION_DDICT_TYPE_LIST",
    "LEDGER_DDICT_BY_NAME",
    "UNION_DDICT_TYPE_LIST",
    "KB_SHALLOW_DDICT_BY_NAME",
    "KB_SHALLOW_DDICT_BY_NAME_TYPE",
]
